Repository memgraph/mage, pull requests merged in 2021-09, with the labels that each got.

#57 Add UUID generator module
  Dockerfile
  README.md
  cpp/CMakeLists.txt
  cpp/uuid_module/CMakeLists.txt
  cpp/uuid_module/uuid_module.cpp
  e2e/uuid_test/test_generation/input.cyp
  e2e/uuid_test/test_generation/test.yml
Labels: lang: cpp, status: ready

#61 Fix betweenness centrality algorithm name typo
  cpp/betweenness_centrality_module/betweenness_centrality_module.cpp
  e2e/betweenness_centrality_test/test_chain_directed/test.yml
  e2e/betweenness_centrality_test/test_chain_normalized/test.yml
  e2e/betweenness_centrality_test/test_chain_undirected/test.yml
  e2e/betweenness_centrality_test/test_complete_graph/test.yml
  e2e/betweenness_centrality_test/test_empty/test.yml
  e2e/betweenness_centrality_test/test_normalized_directed_graph/test.yml
  e2e/betweenness_centrality_test/test_two_nodes/test.yml
Labels: type: bug, status: ready

#63 Change UUID module name to uuid_generator.get()
  README.md
  cpp/uuid_module/CMakeLists.txt
  cpp/uuid_module/uuid_module.cpp
  e2e/uuid_test/test_generation/test.yml
Labels: type: bug, status: ready

#60 Add filtering to E2E tests.
  .gitignore
  README.md
  e2e/database/connection.py
  e2e/database/memgraph.py
  e2e/pytest.ini
  e2e/test_module.py
  python/pytest.ini
  python/tests/requirements.txt
  test_e2e
Labels: type: test, status: ship it

#62 Initial version of checkpoint testing suitable for online algorithms
  e2e/test_module.py
  e2e/weakly_connected_components_test/test_online_adding_components/input.cyp
  e2e/weakly_connected_components_test/test_online_adding_components/test.yml
  e2e/weakly_connected_components_test/test_online_adding_components_no_setup/input.cyp
  e2e/weakly_connected_components_test/test_online_adding_components_no_setup/test.yml
Labels: type: test, status: ready

#67 Remove cargo tarpaulin and local MG download
  .github/workflows/test.yml
Labels: status: discuss it

#65 Reduce docker image size, add black-box script for Docker
  .dockerignore
  .github/workflows/test.yml
  Dockerfile
  README.md
  python/requirements.txt
  setup
Labels: type: enhancement, status: ready
