Repository memgraph/mage, pull requests merged in 2022-11, with the labels that each got.

#161 Node Classification with PyG
  .github/workflows/test.yml
  Dockerfile
  Dockerfile.cugraph
  Dockerfile.release
  e2e/node_classification_online_test/test_online_empty/input.cyp
  e2e/node_classification_online_test/test_online_empty/test.yml
  e2e/node_classification_online_test/test_online_load_non_existing_model/input.cyp
  e2e/node_classification_online_test/test_online_load_non_existing_model/test.yml
  e2e/node_classification_online_test/test_online_predict/input.cyp
  e2e/node_classification_online_test/test_online_predict/test.yml
  e2e/node_classification_online_test/test_online_save_and_load/input.cyp
  e2e/node_classification_online_test/test_online_save_and_load/test.yml
  e2e/node_classification_online_test/test_online_save_without_initialized_model/input.cyp
  e2e/node_classification_online_test/test_online_save_without_initialized_model/test.yml
  e2e/node_classification_online_test/test_online_set_parameters/input.cyp
  e2e/node_classification_online_test/test_online_set_parameters/test.yml
  e2e/node_classification_online_test/test_online_set_parameters_incorrect_type/input.cyp
  e2e/node_classification_online_test/test_online_set_parameters_incorrect_type/test.yml
  e2e/node_classification_online_test/test_online_train_GAT_with_three_layers/input.cyp
  e2e/node_classification_online_test/test_online_train_GAT_with_three_layers/test.yml
  e2e/node_classification_online_test/test_online_train_SAGE_with_two_layers/input.cyp
  e2e/node_classification_online_test/test_online_train_SAGE_with_two_layers/test.yml
  python/mage/node_classification/__init__.py
  python/mage/node_classification/models/__init__.py
  python/mage/node_classification/models/gat.py
  python/mage/node_classification/models/gatjk.py
  python/mage/node_classification/models/gatv2.py
  python/mage/node_classification/models/inductive_model.py
  python/mage/node_classification/models/sage.py
  python/mage/node_classification/models/train_model.py
  python/mage/node_classification/utils/__init__.py
  python/mage/node_classification/utils/extract_from_database.py
  python/mage/node_classification/utils/metrics.py
  python/node_classification.py
  python/requirements.txt
Labels: lang: python, status: ready, type: module

#173 [main < T469-FL] Fix reset, class label and early stopping bugs on node classification module
  e2e/node_classification_online_test/test_online_class_label_no_0/input.cyp
  e2e/node_classification_online_test/test_online_class_label_no_0/test.yml
  e2e/node_classification_online_test/test_online_predict/test.yml
  e2e/node_classification_online_test/test_online_reset/input.cyp
  e2e/node_classification_online_test/test_online_reset/test.yml
  python/mage/node_classification/models/train_model.py
  python/mage/node_classification/utils/extract_from_database.py
  python/node_classification.py
Labels: status: ready

#176 [main < readme_update] Updated git clone to git clone --recurse-submodules
  README.md
Labels: type: docs

#177 Make Graph Coloring output vertices and integers instead of strings
  e2e/graph_coloring_test/test_convergence_callback/test.yml
  e2e/graph_coloring_test/test_graph_init_algorithms/test.yml
  e2e/graph_coloring_test/test_graph_one_node/test.yml
  e2e/graph_coloring_test/test_graph_parallel/test.yml
  e2e/graph_coloring_test/test_graph_without_weight/test.yml
  e2e/graph_coloring_test/test_large_graph/test.yml
  e2e/graph_coloring_test/test_multiple_mutation/test.yml
  e2e/graph_coloring_test/test_random_mutation/test.yml
  python/graph_coloring.py
Labels: type: enhancement, status: ship it
