Repository memgraph/mage, pull requests merged in 2022-06, with the labels that each got.

#148 Fix Rust CI build
  setup
Labels: type: bug

#147 Dynamic betweenness centrality bugfix
  cpp/betweenness_centrality_module/algorithm_online/betweenness_centrality_online.cpp
  cpp/betweenness_centrality_module/algorithm_online/betweenness_centrality_online.hpp
  cpp/betweenness_centrality_module/betweenness_centrality_online_module.cpp
  e2e/betweenness_centrality_online_test/test_online_get/input.cyp
  setup
Labels: type: bug, lang: cpp, status: ready

#144 Update links on README
  README.md
Labels: status: ready
