Repository memgraph/mage, pull requests merged in 2023-10, with the labels that each got.

#372 [E-refactor < T661] CloneNodesWithRelationships small refactor
  cpp/refactor_module/algorithm/refactor.cpp
  cpp/refactor_module/algorithm/refactor.hpp
  e2e_correctness/refactor_test/test_clone_nodes1/test.yml
  e2e_correctness/refactor_test/test_clone_nodes2/test.yml
  e2e_correctness/refactor_test/test_clone_nodes3/test.yml
  e2e_correctness/refactor_test/test_clone_nodes4/input.cyp
  e2e_correctness/refactor_test/test_clone_nodes4/test.yml
Labels: Docs unnecessary

#368 [E-path < T489-T491] Add path combine, slice and elements
  cpp/path_module/algorithm/path.cpp
  cpp/path_module/algorithm/path.hpp
  cpp/path_module/path_module.cpp
  e2e/path_test/test_elements_1/input.cyp
  e2e/path_test/test_elements_1/test.yml
  e2e/path_test/test_elements_2/input.cyp
  e2e/path_test/test_elements_2/test.yml
  e2e_correctness/path_test/test_combine_1/config.yml
  e2e_correctness/path_test/test_combine_1/input.cyp
  e2e_correctness/path_test/test_combine_1/test.yml
  e2e_correctness/path_test/test_combine_2/config.yml
  e2e_correctness/path_test/test_combine_2/input.cyp
  e2e_correctness/path_test/test_combine_2/test.yml
  e2e_correctness/path_test/test_slice_1/config.yml
  e2e_correctness/path_test/test_slice_1/input.cyp
  e2e_correctness/path_test/test_slice_1/test.yml
  e2e_correctness/path_test/test_slice_2/config.yml
  e2e_correctness/path_test/test_slice_2/input.cyp
  e2e_correctness/path_test/test_slice_2/test.yml
  e2e_correctness/path_test/test_slice_3/config.yml
  e2e_correctness/path_test/test_slice_3/input.cyp
  e2e_correctness/path_test/test_slice_3/test.yml
Labels: type: module, status: ship it, Needs new memgraph

#367 [E-refactor < T374] Add refactor.normalize_as_boolean
  cpp/refactor_module/CMakeLists.txt
  cpp/refactor_module/algorithm/refactor.cpp
  cpp/refactor_module/algorithm/refactor.hpp
  cpp/refactor_module/refactor_module.cpp
  e2e_correctness/refactor_test/test_normalize_as_boolean_1/input.cyp
  e2e_correctness/refactor_test/test_normalize_as_boolean_1/test.yml
  e2e_correctness/refactor_test/test_normalize_as_boolean_2/input.cyp
  e2e_correctness/refactor_test/test_normalize_as_boolean_2/test.yml
  e2e_correctness/refactor_test/test_normalize_as_boolean_3/input.cyp
  e2e_correctness/refactor_test/test_normalize_as_boolean_3/test.yml
  e2e_correctness/refactor_test/test_normalize_as_boolean_4/input.cyp
  e2e_correctness/refactor_test/test_normalize_as_boolean_4/test.yml
  e2e_correctness/refactor_test/test_normalize_as_boolean_5/input.cyp
  e2e_correctness/refactor_test/test_normalize_as_boolean_5/test.yml
  python/tests/requirements.txt
Labels: type: module, status: ship it

#364 [E-refactor < T371] Add refactor.extract_node
  cpp/refactor_module/algorithm/refactor.cpp
  cpp/refactor_module/algorithm/refactor.hpp
  cpp/refactor_module/refactor_module.cpp
  e2e/refactor_test/test_extract_node_id/input.cyp
  e2e/refactor_test/test_extract_node_id/test.yml
  e2e/refactor_test/test_extract_node_ids/input.cyp
  e2e/refactor_test/test_extract_node_ids/test.yml
  e2e/refactor_test/test_extract_node_rel/input.cyp
  e2e/refactor_test/test_extract_node_rel/test.yml
  e2e/refactor_test/test_extract_node_rels/input.cyp
  e2e/refactor_test/test_extract_node_rels/test.yml
Labels: type: module, status: ship it

#392 [main < T] Fix failing tests
  python/tests/requirements.txt
Labels: status: ship it, Docs unnecessary

#393 [main < T]Add memory dispatcher guard
  cpp/collections_module/algorithm/collections.cpp
  cpp/collections_module/collections_module.cpp
  cpp/community_detection_module/community_detection_online_module.cpp
  cpp/create_module/algorithm/create.cpp
  cpp/create_module/create_module.cpp
  cpp/distance_calculator/distance_calculator.cpp
  cpp/do_module/do_module.cpp
  cpp/graph_util_module/algorithms/ancestors.hpp
  cpp/graph_util_module/algorithms/chain_nodes.hpp
  cpp/graph_util_module/algorithms/connect_nodes.hpp
  cpp/graph_util_module/algorithms/descendants.hpp
  cpp/graph_util_module/algorithms/topological_sort.hpp
  cpp/graph_util_module/graph_util_module.cpp
  cpp/katz_centrality_module/katz_centrality_online_module.cpp
  cpp/label_module/algorithm/label.cpp
  cpp/label_module/label_module.cpp
  cpp/map_module/algorithm/map.cpp
  cpp/map_module/map_module.cpp
  cpp/neighbors_module/algorithm/neighbors.cpp
  cpp/neighbors_module/neighbors_module.cpp
  cpp/node_module/algorithm/node.cpp
  cpp/node_module/node_module.cpp
  cpp/node_similarity_module/node_similarity_module.cpp
  cpp/nodes_module/algorithm/nodes.cpp
  cpp/nodes_module/nodes_module.cpp
  cpp/pagerank_module/pagerank_online_module.cpp
  cpp/path_module/algorithm/path.cpp
  cpp/path_module/path_module.cpp
  cpp/periodic_module/periodic_iterate.cpp
  cpp/refactor_module/algorithm/refactor.cpp
  cpp/schema_module/algorithm/schema.cpp
  cpp/schema_module/schema_module.cpp
  cpp/text_module/algorithm/text.cpp
  cpp/text_module/text_module.cpp
  cpp/util_module/algorithm/util.cpp
  cpp/util_module/util_module.cpp
Labels: status: ship it, Docs unnecessary

#386 [main < T676] Ignore libmgclient while copying query modules
  setup
Labels: type: bug, Docs unnecessary

#397 [main < unofficial-build] Unofficial 2.12 build
  .github/workflows/test.yml
  .gitmodules
  e2e/collections_test/test_to_set1/test.yml
  e2e/collections_test/test_to_set2/test.yml
  e2e/collections_test/test_to_set3/input.cyp
  e2e/collections_test/test_to_set3/test.yml
Labels: infrastructure

#389 [E-algo < T581] Implement algo.cover
  cpp/algo_module/algo_module.cpp
  cpp/algo_module/algorithm/algo.cpp
  cpp/algo_module/algorithm/algo.hpp
  e2e/algo_test/test_cover1/input.cyp
  e2e/algo_test/test_cover1/test.yml
  e2e/algo_test/test_cover2/input.cyp
  e2e/algo_test/test_cover2/test.yml
  e2e/algo_test/test_cover3/input.cyp
  e2e/algo_test/test_cover3/test.yml
Labels: status: ship it, Docs needed

#370 [E-path < T667-T668] Path subgraph improvement and path refactor
  cpp/path_module/algorithm/path.cpp
  cpp/path_module/algorithm/path.hpp
  cpp/path_module/path_module.cpp
  e2e/path_test/test_expand1/test.yml
  e2e/path_test/test_expand2/test.yml
  e2e/path_test/test_expand3/test.yml
  e2e/path_test/test_expand4/test.yml
  e2e/path_test/test_subgraph_all_1/test.yml
  e2e/path_test/test_subgraph_all_2/test.yml
  e2e/path_test/test_subgraph_all_3/test.yml
  e2e/path_test/test_subgraph_nodes_1/test.yml
  e2e/path_test/test_subgraph_nodes_2/test.yml
  e2e/path_test/test_subgraph_nodes_3/test.yml
Labels: enhancement, status: ship it, Needs new memgraph

#373 [E-refactor < T662] Implement refactor.delete_and_reconnect
  cpp/refactor_module/algorithm/refactor.cpp
  cpp/refactor_module/algorithm/refactor.hpp
  cpp/refactor_module/refactor_module.cpp
  e2e_correctness/refactor_test/test_delete_and_reconnect_1/input.cyp
  e2e_correctness/refactor_test/test_delete_and_reconnect_1/test.yml
  e2e_correctness/refactor_test/test_delete_and_reconnect_2/input.cyp
  e2e_correctness/refactor_test/test_delete_and_reconnect_2/test.yml
  e2e_correctness/refactor_test/test_delete_and_reconnect_3/input.cyp
  e2e_correctness/refactor_test/test_delete_and_reconnect_3/test.yml
  e2e_correctness/refactor_test/test_delete_and_reconnect_4/input.cyp
  e2e_correctness/refactor_test/test_delete_and_reconnect_4/test.yml
  e2e_correctness/refactor_test/test_delete_and_reconnect_5/input.cyp
  e2e_correctness/refactor_test/test_delete_and_reconnect_5/test.yml
  e2e_correctness/refactor_test/test_delete_and_reconnect_6/input.cyp
  e2e_correctness/refactor_test/test_delete_and_reconnect_6/test.yml
  e2e_correctness/refactor_test/test_delete_and_reconnect_7/input.cyp
  e2e_correctness/refactor_test/test_delete_and_reconnect_7/test.yml
  e2e_correctness/refactor_test/test_delete_and_reconnect_8/input.cyp
  e2e_correctness/refactor_test/test_delete_and_reconnect_8/test.yml
Labels: type: module, status: ship it

#377 [main < T] Bugfix for map.merge
  cpp/map_module/algorithm/map.cpp
Labels: type: bug, status: ship it, Needs new memgraph, Docs unnecessary

#369 [main < T- degree] Implement node in out degree
  cpp/node_module/algorithm/node.cpp
  cpp/node_module/algorithm/node.hpp
  cpp/node_module/node_module.cpp
  e2e/node_test/test_degree_in1/input.cyp
  e2e/node_test/test_degree_in1/test.yml
  e2e/node_test/test_degree_in2/input.cyp
  e2e/node_test/test_degree_in2/test.yml
  e2e/node_test/test_degree_in3/input.cyp
  e2e/node_test/test_degree_in3/test.yml
  e2e/node_test/test_degree_out1/input.cyp
  e2e/node_test/test_degree_out1/test.yml
  e2e/node_test/test_degree_out2/input.cyp
  e2e/node_test/test_degree_out2/test.yml
  e2e/node_test/test_degree_out3/input.cyp
  e2e/node_test/test_degree_out3/test.yml
Labels: status: ship it, Docs needed

#388 [E-refactor < T381] Implement rename type property
  cpp/refactor_module/algorithm/refactor.cpp
  cpp/refactor_module/algorithm/refactor.hpp
  cpp/refactor_module/refactor_module.cpp
  e2e_correctness/refactor_test/test_rename_type_prop1/input.cyp
  e2e_correctness/refactor_test/test_rename_type_prop1/test.yml
  e2e_correctness/refactor_test/test_rename_type_prop2/input.cyp
  e2e_correctness/refactor_test/test_rename_type_prop2/test.yml
  e2e_correctness/refactor_test/test_rename_type_prop3/input.cyp
  e2e_correctness/refactor_test/test_rename_type_prop3/test.yml
Labels: status: ship it, Docs needed

#391 [E-merge < T674] Implement merge.node
  cpp/merge_module/algorithm/merge.cpp
  cpp/merge_module/algorithm/merge.hpp
  cpp/merge_module/merge_module.cpp
  e2e_correctness/merge_test/test_node1/input.cyp
  e2e_correctness/merge_test/test_node1/test.yml
  e2e_correctness/merge_test/test_node2/input.cyp
  e2e_correctness/merge_test/test_node2/test.yml
  e2e_correctness/merge_test/test_node3/input.cyp
  e2e_correctness/merge_test/test_node3/test.yml
  e2e_correctness/merge_test/test_node4/input.cyp
  e2e_correctness/merge_test/test_node4/test.yml
  e2e_correctness/merge_test/test_node5/input.cyp
  e2e_correctness/merge_test/test_node5/test.yml
  e2e_correctness/merge_test/test_node6/input.cyp
  e2e_correctness/merge_test/test_node6/test.yml
Labels: status: ship it, Docs needed

#394 [main < E-path] Add path functions
  cpp/path_module/algorithm/path.cpp
  cpp/path_module/algorithm/path.hpp
  cpp/path_module/path_module.cpp
  e2e/path_test/test_elements_1/input.cyp
  e2e/path_test/test_elements_1/test.yml
  e2e/path_test/test_elements_2/input.cyp
  e2e/path_test/test_elements_2/test.yml
  e2e/path_test/test_expand1/test.yml
  e2e/path_test/test_expand2/test.yml
  e2e/path_test/test_expand3/test.yml
  e2e/path_test/test_expand4/test.yml
  e2e/path_test/test_subgraph_all_1/test.yml
  e2e/path_test/test_subgraph_all_2/test.yml
  e2e/path_test/test_subgraph_all_3/test.yml
  e2e/path_test/test_subgraph_nodes_1/test.yml
  e2e/path_test/test_subgraph_nodes_2/test.yml
  e2e/path_test/test_subgraph_nodes_3/test.yml
  e2e_correctness/path_test/test_combine_1/config.yml
  e2e_correctness/path_test/test_combine_1/input.cyp
  e2e_correctness/path_test/test_combine_1/test.yml
  e2e_correctness/path_test/test_combine_2/config.yml
  e2e_correctness/path_test/test_combine_2/input.cyp
  e2e_correctness/path_test/test_combine_2/test.yml
  e2e_correctness/path_test/test_slice_1/config.yml
  e2e_correctness/path_test/test_slice_1/input.cyp
  e2e_correctness/path_test/test_slice_1/test.yml
  e2e_correctness/path_test/test_slice_2/config.yml
  e2e_correctness/path_test/test_slice_2/input.cyp
  e2e_correctness/path_test/test_slice_2/test.yml
  e2e_correctness/path_test/test_slice_3/config.yml
  e2e_correctness/path_test/test_slice_3/input.cyp
  e2e_correctness/path_test/test_slice_3/test.yml
Labels: type: module, status: ship it, Docs needed

#403 [main < T] Delete query modules
  cpp/CMakeLists.txt
  cpp/schema_module/CMakeLists.txt
  cpp/schema_module/algorithm/schema.cpp
  cpp/schema_module/algorithm/schema.hpp
  cpp/schema_module/schema_module.cpp
  e2e/convert_test/test_str2object1/file1
  e2e/convert_test/test_str2object1/input.cyp
  e2e/convert_test/test_str2object1/test.yml
  e2e/schema_test/test_node_type_properties1/input.cyp
  e2e/schema_test/test_node_type_properties1/test.yml
  e2e/schema_test/test_node_type_properties2/input.cyp
  e2e/schema_test/test_node_type_properties2/test.yml
  e2e/schema_test/test_node_type_properties3/input.cyp
  e2e/schema_test/test_node_type_properties3/test.yml
  e2e/schema_test/test_rel_type_properties1/input.cyp
  e2e/schema_test/test_rel_type_properties1/test.yml
  e2e/schema_test/test_rel_type_properties2/input.cyp
  e2e/schema_test/test_rel_type_properties2/test.yml
  e2e/schema_test/test_rel_type_properties3/input.cyp
  e2e/schema_test/test_rel_type_properties3/test.yml
  python/convert.py
  python/mgps.py
Labels: status: ready, Docs unnecessary

#353 [main < E-algo] Add algo query module
  cpp/CMakeLists.txt
  cpp/algo_module/CMakeLists.txt
  cpp/algo_module/algo_module.cpp
  cpp/algo_module/algorithm/algo.cpp
  cpp/algo_module/algorithm/algo.hpp
  e2e/algo_test/test_cover1/input.cyp
  e2e/algo_test/test_cover1/test.yml
  e2e/algo_test/test_cover2/input.cyp
  e2e/algo_test/test_cover2/test.yml
  e2e/algo_test/test_cover3/input.cyp
  e2e/algo_test/test_cover3/test.yml
Labels: type: module, In progress, Docs needed

#371 [main < T516] Implement astar algorithm
  cpp/algo_module/algo_module.cpp
  cpp/algo_module/algorithm/algo.cpp
  cpp/algo_module/algorithm/algo.hpp
  e2e/algo_test/test_astar_cutsom_heur/input.cyp
  e2e/algo_test/test_astar_cutsom_heur/test.yml
  e2e/algo_test/test_astar_temporal_type/input.cyp
  e2e/algo_test/test_astar_temporal_type/test.yml
  e2e_correctness/algo_test/test_astar_normal/config.yml
  e2e_correctness/algo_test/test_astar_normal/input.cyp
  e2e_correctness/algo_test/test_astar_normal/test.yml
  e2e_correctness/algo_test/test_astar_normal_double/config.yml
  e2e_correctness/algo_test/test_astar_normal_double/input.cyp
  e2e_correctness/algo_test/test_astar_normal_double/test.yml
  e2e_correctness/algo_test/test_astar_rel_filter/config.yml
  e2e_correctness/algo_test/test_astar_rel_filter/input.cyp
  e2e_correctness/algo_test/test_astar_rel_filter/test.yml
Labels: status: ship it, Docs needed

#376 [main < E-refactor] Add refactor functions
  cpp/refactor_module/CMakeLists.txt
  cpp/refactor_module/algorithm/refactor.cpp
  cpp/refactor_module/algorithm/refactor.hpp
  cpp/refactor_module/refactor_module.cpp
  e2e/refactor_test/test_extract_node_id/input.cyp
  e2e/refactor_test/test_extract_node_id/test.yml
  e2e/refactor_test/test_extract_node_ids/input.cyp
  e2e/refactor_test/test_extract_node_ids/test.yml
  e2e/refactor_test/test_extract_node_rel/input.cyp
  e2e/refactor_test/test_extract_node_rel/test.yml
  e2e/refactor_test/test_extract_node_rels/input.cyp
  e2e/refactor_test/test_extract_node_rels/test.yml
  e2e_correctness/refactor_test/test_clone_nodes1/test.yml
  e2e_correctness/refactor_test/test_clone_nodes2/test.yml
  e2e_correctness/refactor_test/test_clone_nodes3/test.yml
  e2e_correctness/refactor_test/test_clone_nodes4/input.cyp
  e2e_correctness/refactor_test/test_clone_nodes4/test.yml
  e2e_correctness/refactor_test/test_delete_and_reconnect_1/input.cyp
  e2e_correctness/refactor_test/test_delete_and_reconnect_1/test.yml
  e2e_correctness/refactor_test/test_delete_and_reconnect_2/input.cyp
  e2e_correctness/refactor_test/test_delete_and_reconnect_2/test.yml
  e2e_correctness/refactor_test/test_delete_and_reconnect_3/input.cyp
  e2e_correctness/refactor_test/test_delete_and_reconnect_3/test.yml
  e2e_correctness/refactor_test/test_delete_and_reconnect_4/input.cyp
  e2e_correctness/refactor_test/test_delete_and_reconnect_4/test.yml
  e2e_correctness/refactor_test/test_delete_and_reconnect_5/input.cyp
  e2e_correctness/refactor_test/test_delete_and_reconnect_5/test.yml
  e2e_correctness/refactor_test/test_delete_and_reconnect_6/input.cyp
  e2e_correctness/refactor_test/test_delete_and_reconnect_6/test.yml
  e2e_correctness/refactor_test/test_delete_and_reconnect_7/input.cyp
  e2e_correctness/refactor_test/test_delete_and_reconnect_7/test.yml
  e2e_correctness/refactor_test/test_delete_and_reconnect_8/input.cyp
  e2e_correctness/refactor_test/test_delete_and_reconnect_8/test.yml
  e2e_correctness/refactor_test/test_normalize_as_boolean_1/input.cyp
  e2e_correctness/refactor_test/test_normalize_as_boolean_1/test.yml
  e2e_correctness/refactor_test/test_normalize_as_boolean_2/input.cyp
  e2e_correctness/refactor_test/test_normalize_as_boolean_2/test.yml
  e2e_correctness/refactor_test/test_normalize_as_boolean_3/input.cyp
  e2e_correctness/refactor_test/test_normalize_as_boolean_3/test.yml
  e2e_correctness/refactor_test/test_normalize_as_boolean_4/input.cyp
  e2e_correctness/refactor_test/test_normalize_as_boolean_4/test.yml
  e2e_correctness/refactor_test/test_normalize_as_boolean_5/input.cyp
  e2e_correctness/refactor_test/test_normalize_as_boolean_5/test.yml
  e2e_correctness/refactor_test/test_rename_type_1/input.cyp
  e2e_correctness/refactor_test/test_rename_type_1/test.yml
  e2e_correctness/refactor_test/test_rename_type_2/input.cyp
  e2e_correctness/refactor_test/test_rename_type_2/test.yml
  e2e_correctness/refactor_test/test_rename_type_3/input.cyp
  e2e_correctness/refactor_test/test_rename_type_3/test.yml
  e2e_correctness/refactor_test/test_rename_type_prop1/input.cyp
  e2e_correctness/refactor_test/test_rename_type_prop1/test.yml
  e2e_correctness/refactor_test/test_rename_type_prop2/input.cyp
  e2e_correctness/refactor_test/test_rename_type_prop2/test.yml
  e2e_correctness/refactor_test/test_rename_type_prop3/input.cyp
  e2e_correctness/refactor_test/test_rename_type_prop3/test.yml
Labels: type: module, status: ship it, Docs needed

#402 [main <T] Fix neighbors.at_hop bug
  cpp/neighbors_module/algorithm/neighbors.cpp
Labels: type: bug, status: ready, Docs unnecessary

#401 Add CSV utility functions used in the Lab CSV import feature
  cpp/CMakeLists.txt
  cpp/csv_utils_module/CMakeLists.txt
  cpp/csv_utils_module/algorithm/csv_utils.cpp
  cpp/csv_utils_module/algorithm/csv_utils.hpp
  cpp/csv_utils_module/csv_utils_module.cpp
Labels: status: change

#356 [main < T518] Add algo.all_simple_paths
  cpp/algo_module/algo_module.cpp
  cpp/algo_module/algorithm/algo.cpp
  cpp/algo_module/algorithm/algo.hpp
  e2e_correctness/algo_test/test_path_all_simple_paths_1/input.cyp
  e2e_correctness/algo_test/test_path_all_simple_paths_1/test.yml
  e2e_correctness/algo_test/test_path_all_simple_paths_10/input.cyp
  e2e_correctness/algo_test/test_path_all_simple_paths_10/test.yml
  e2e_correctness/algo_test/test_path_all_simple_paths_2/input.cyp
  e2e_correctness/algo_test/test_path_all_simple_paths_2/test.yml
  e2e_correctness/algo_test/test_path_all_simple_paths_3/input.cyp
  e2e_correctness/algo_test/test_path_all_simple_paths_3/test.yml
  e2e_correctness/algo_test/test_path_all_simple_paths_4/input.cyp
  e2e_correctness/algo_test/test_path_all_simple_paths_4/test.yml
  e2e_correctness/algo_test/test_path_all_simple_paths_5/input.cyp
  e2e_correctness/algo_test/test_path_all_simple_paths_5/test.yml
  e2e_correctness/algo_test/test_path_all_simple_paths_6/input.cyp
  e2e_correctness/algo_test/test_path_all_simple_paths_6/test.yml
  e2e_correctness/algo_test/test_path_all_simple_paths_7/input.cyp
  e2e_correctness/algo_test/test_path_all_simple_paths_7/test.yml
  e2e_correctness/algo_test/test_path_all_simple_paths_8/input.cyp
  e2e_correctness/algo_test/test_path_all_simple_paths_8/test.yml
  e2e_correctness/algo_test/test_path_all_simple_paths_9/input.cyp
  e2e_correctness/algo_test/test_path_all_simple_paths_9/test.yml
Labels: status: ship it, Docs needed

#390 [main < E-merge] Create merge query module
  cpp/CMakeLists.txt
  cpp/merge_module/CMakeLists.txt
  cpp/merge_module/algorithm/merge.cpp
  cpp/merge_module/algorithm/merge.hpp
  cpp/merge_module/merge_module.cpp
  e2e_correctness/merge_test/test_node1/input.cyp
  e2e_correctness/merge_test/test_node1/test.yml
  e2e_correctness/merge_test/test_node2/input.cyp
  e2e_correctness/merge_test/test_node2/test.yml
  e2e_correctness/merge_test/test_node3/input.cyp
  e2e_correctness/merge_test/test_node3/test.yml
  e2e_correctness/merge_test/test_node4/input.cyp
  e2e_correctness/merge_test/test_node4/test.yml
  e2e_correctness/merge_test/test_node5/input.cyp
  e2e_correctness/merge_test/test_node5/test.yml
  e2e_correctness/merge_test/test_node6/input.cyp
  e2e_correctness/merge_test/test_node6/test.yml
  e2e_correctness/merge_test/test_relationship_1/input.cyp
  e2e_correctness/merge_test/test_relationship_1/test.yml
  e2e_correctness/merge_test/test_relationship_2/input.cyp
  e2e_correctness/merge_test/test_relationship_2/test.yml
  e2e_correctness/merge_test/test_relationship_3/input.cyp
  e2e_correctness/merge_test/test_relationship_3/test.yml
Labels: status: ship it, Docs needed
