Repository memgraph/mage, pull requests merged in 2023-09, with the labels that each got.

#296 [main < T584] Implement meta.stats
  cpp/CMakeLists.txt
  cpp/meta_module/CMakeLists.txt
  cpp/meta_module/algorithm/meta.cpp
  cpp/meta_module/algorithm/meta.hpp
  cpp/meta_module/meta_module.cpp
  e2e/meta_online_test/test_online_stats_1/input.cyp
  e2e/meta_online_test/test_online_stats_1/test.yml
  e2e/meta_online_test/test_online_stats_2/input.cyp
  e2e/meta_online_test/test_online_stats_2/test.yml
  e2e/meta_online_test/test_online_stats_3/input.cyp
  e2e/meta_online_test/test_online_stats_3/test.yml
  e2e/meta_online_test/test_online_stats_4/input.cyp
  e2e/meta_online_test/test_online_stats_4/test.yml
  e2e/meta_online_test/test_online_stats_5/input.cyp
  e2e/meta_online_test/test_online_stats_5/test.yml
  e2e/meta_online_test/test_online_stats_detach_delete/input.cyp
  e2e/meta_online_test/test_online_stats_detach_delete/test.yml
  e2e/meta_online_test/test_online_stats_update_1/input.cyp
  e2e/meta_online_test/test_online_stats_update_1/test.yml
  e2e/meta_online_test/test_online_stats_update_2/input.cyp
  e2e/meta_online_test/test_online_stats_update_2/test.yml
  e2e/meta_online_test/test_online_stats_update_3/input.cyp
  e2e/meta_online_test/test_online_stats_update_3/test.yml
  e2e/meta_online_test/test_online_stats_update_4/input.cyp
  e2e/meta_online_test/test_online_stats_update_4/test.yml
  e2e/meta_online_test/test_online_stats_update_5/input.cyp
  e2e/meta_online_test/test_online_stats_update_5/test.yml
  e2e/meta_test/test_stats_1/input.cyp
  e2e/meta_test/test_stats_1/test.yml
  e2e/meta_test/test_stats_2/input.cyp
  e2e/meta_test/test_stats_2/test.yml
  e2e/meta_test/test_stats_3/input.cyp
  e2e/meta_test/test_stats_3/test.yml
  e2e/meta_test/test_stats_4/input.cyp
  e2e/meta_test/test_stats_4/test.yml
  e2e/meta_test/test_stats_5/input.cyp
  e2e/meta_test/test_stats_5/test.yml
Labels: status: ready, status: ship it

#317 [E-path < T488] Add path.create
  cpp/path_module/algorithm/path.cpp
  cpp/path_module/algorithm/path.hpp
  cpp/path_module/path_module.cpp
  e2e/path_test/test_create_1/input.cyp
  e2e/path_test/test_create_1/test.yml
  e2e/path_test/test_create_2/input.cyp
  e2e/path_test/test_create_2/test.yml
  e2e/path_test/test_create_3/input.cyp
  e2e/path_test/test_create_3/test.yml
Labels: status: discuss it

#312 [main < E -nodes] Merge nodes module into main
  cpp/CMakeLists.txt
  cpp/nodes_module/CMakeLists.txt
  cpp/nodes_module/algorithm/nodes.cpp
  cpp/nodes_module/algorithm/nodes.hpp
  cpp/nodes_module/nodes_module.cpp
  e2e/nodes_test/test_relationship_types_id/input.cyp
  e2e/nodes_test/test_relationship_types_id/test.yml
  e2e/nodes_test/test_relationship_types_ids/input.cyp
  e2e/nodes_test/test_relationship_types_ids/test.yml
  e2e/nodes_test/test_relationship_types_node/input.cyp
  e2e/nodes_test/test_relationship_types_node/test.yml
  e2e/nodes_test/test_relationship_types_nodes/input.cyp
  e2e/nodes_test/test_relationship_types_nodes/test.yml
  e2e/nodes_test/test_relationships_exist1/input.cyp
  e2e/nodes_test/test_relationships_exist1/test.yml
  e2e/nodes_test/test_relationships_exist2/input.cyp
  e2e/nodes_test/test_relationships_exist2/test.yml
  e2e/nodes_test/test_relationships_exist3/input.cyp
  e2e/nodes_test/test_relationships_exist3/test.yml
  e2e_correctness/nodes_test/test_delete_id/input.cyp
  e2e_correctness/nodes_test/test_delete_id/test.yml
  e2e_correctness/nodes_test/test_delete_ids/input.cyp
  e2e_correctness/nodes_test/test_delete_ids/test.yml
  e2e_correctness/nodes_test/test_delete_node/input.cyp
  e2e_correctness/nodes_test/test_delete_node/test.yml
  e2e_correctness/nodes_test/test_delete_nodes/input.cyp
  e2e_correctness/nodes_test/test_delete_nodes/test.yml
  e2e_correctness/nodes_test/test_link1/input.cyp
  e2e_correctness/nodes_test/test_link1/test.yml
  e2e_correctness/nodes_test/test_link2/input.cyp
  e2e_correctness/nodes_test/test_link2/test.yml
  e2e_correctness/nodes_test/test_link3/input.cyp
  e2e_correctness/nodes_test/test_link3/test.yml
Labels: status: ship it

#313 [main < E-path] Merge path functions into main
  cpp/CMakeLists.txt
  cpp/path_module/CMakeLists.txt
  cpp/path_module/algorithm/path.cpp
  cpp/path_module/algorithm/path.hpp
  cpp/path_module/path_module.cpp
  e2e/path_test/test_create_1/input.cyp
  e2e/path_test/test_create_1/test.yml
  e2e/path_test/test_create_2/input.cyp
  e2e/path_test/test_create_2/test.yml
  e2e/path_test/test_create_3/input.cyp
  e2e/path_test/test_create_3/test.yml
  e2e/path_test/test_expand1/input.cyp
  e2e/path_test/test_expand1/test.yml
  e2e/path_test/test_expand2/input.cyp
  e2e/path_test/test_expand2/test.yml
  e2e/path_test/test_expand3/input.cyp
  e2e/path_test/test_expand3/test.yml
  e2e/path_test/test_expand4/input.cyp
  e2e/path_test/test_expand4/test.yml
Labels: status: ship it

#311 [main < E-util] Merge util module(single function) to main
  cpp/CMakeLists.txt
  cpp/util_module/CMakeLists.txt
  cpp/util_module/algorithm/md5.cpp
  cpp/util_module/algorithm/md5.hpp
  cpp/util_module/algorithm/util.cpp
  cpp/util_module/algorithm/util.hpp
  cpp/util_module/util_module.cpp
  e2e/util_module_online_test/test_online_util1/input.cyp
  e2e/util_module_online_test/test_online_util1/test.yml
  e2e/util_module_test/util_test1/input.cyp
  e2e/util_module_test/util_test1/test.yml
  e2e/util_module_test/util_test2/input.cyp
  e2e/util_module_test/util_test2/test.yml
  e2e/util_module_test/util_test3/input.cyp
  e2e/util_module_test/util_test3/test.yml
Labels: type: module, status: ship it

#332 [main < T] Small naming fix
  e2e/node_test/test_relationshipsExist1/input.cyp
  e2e/node_test/test_relationshipsExist1/test.yml
Labels: status: ready

#325 [E-export < T338] Implement export_csv_graph
  e2e/export_util_test/test_csv_graph_exporting_1/input.cyp
  e2e/export_util_test/test_csv_graph_exporting_1/test.yml
  e2e/export_util_test/test_csv_graph_exporting_2/input.cyp
  e2e/export_util_test/test_csv_graph_exporting_2/test.yml
  python/export_util.py
Labels: status: ready, type: module

#331 [E-idora < T366] Implement refactor.categorize
  cpp/refactor_module/algorithm/refactor.cpp
  cpp/refactor_module/algorithm/refactor.hpp
  cpp/refactor_module/refactor_module.cpp
  e2e/refactor_test/test_online_categorize_1/input.cyp
  e2e/refactor_test/test_online_categorize_1/test.yml
  e2e/refactor_test/test_online_categorize_2/input.cyp
  e2e/refactor_test/test_online_categorize_2/test.yml
  e2e/refactor_test/test_online_categorize_3/input.cyp
  e2e/refactor_test/test_online_categorize_3/test.yml
Labels: type: module, status: ship it, status: checks failing

#329 [main < T load, parse] Implement xml.load and xml.parse
  cpp/CMakeLists.txt
  e2e/xml_test/load_test1/input.cyp
  e2e/xml_test/load_test1/test.yml
  e2e/xml_test/load_test2/input.cyp
  e2e/xml_test/load_test2/test.yml
  e2e/xml_test/load_test3/input.cyp
  e2e/xml_test/load_test3/test.yml
  e2e/xml_test/parse_test1/input.cyp
  e2e/xml_test/parse_test1/test.yml
  e2e/xml_test/parse_test2/input.cyp
  e2e/xml_test/parse_test2/test.yml
  e2e/xml_test/parse_test3/input.cyp
  e2e/xml_test/parse_test3/test.yml
  python/requirements.txt
  python/xml_module.py
Labels: type: module, status: ship it

#326 [main < T622] Add convert str2object
  e2e/convert_test/test_str2object1/file1
  e2e/convert_test/test_str2object1/input.cyp
  e2e/convert_test/test_str2object1/test.yml
  python/convert.py
Labels: type: module, status: discuss it, status: ship it

#346 [main < test-module-bugfix] Fix small bug on test module
  e2e/test_module.py
Labels: type: bug, status: ship it

#340 [main < T483-MAGE] Implement path.subgraph_nodes and path.subgraph_all
  cpp/path_module/algorithm/path.cpp
  cpp/path_module/algorithm/path.hpp
  cpp/path_module/path_module.cpp
  e2e/path_test/test_subgraph_all_1/input.cyp
  e2e/path_test/test_subgraph_all_1/test.yml
  e2e/path_test/test_subgraph_all_2/input.cyp
  e2e/path_test/test_subgraph_all_2/test.yml
  e2e/path_test/test_subgraph_all_3/input.cyp
  e2e/path_test/test_subgraph_all_3/test.yml
  e2e/path_test/test_subgraph_nodes_1/input.cyp
  e2e/path_test/test_subgraph_nodes_1/test.yml
  e2e/path_test/test_subgraph_nodes_2/input.cyp
  e2e/path_test/test_subgraph_nodes_2/test.yml
  e2e/path_test/test_subgraph_nodes_3/input.cyp
  e2e/path_test/test_subgraph_nodes_3/test.yml
Labels: type: module, status: ship it

#345 [E-refactor < T378-T379] Add rename.label and rename.node_property
  cpp/refactor_module/algorithm/refactor.cpp
  cpp/refactor_module/algorithm/refactor.hpp
  cpp/refactor_module/refactor_module.cpp
  e2e/refactor_test/test_rename_label/input.cyp
  e2e/refactor_test/test_rename_label/test.yml
  e2e/refactor_test/test_rename_property_nodes/input.cyp
  e2e/refactor_test/test_rename_property_nodes/test.yml
  e2e_correctness/refactor_test/test_rename_label/input.cyp
  e2e_correctness/refactor_test/test_rename_label/test.yml
  e2e_correctness/refactor_test/test_rename_property_nodes/input.cyp
  e2e_correctness/refactor_test/test_rename_property_nodes/test.yml
Labels: type: module, status: ship it

#327 [main < T350-MAGE] Implement graphml import and export
  e2e/graphml_test/test_export/input.cyp
  e2e/graphml_test/test_export/test.yml
  python/export_util.py
  python/import_util.py
Labels: type: module, status: ship it, status: checks failing

#335 [E-idora < T368, T369] Implement refactor.clone_subgraph and subgraph_from_path
  cpp/meta_module/algorithm/meta.cpp
  cpp/meta_module/meta_module.cpp
  cpp/refactor_module/algorithm/refactor.cpp
  cpp/refactor_module/algorithm/refactor.hpp
  cpp/refactor_module/refactor_module.cpp
  e2e/graphml_test/test_export/input.cyp
  e2e/graphml_test/test_export/test.yml
  e2e/refactor_test/test_clone_subgraph_1/input.cyp
  e2e/refactor_test/test_clone_subgraph_1/test.yml
  e2e/refactor_test/test_clone_subgraph_2/input.cyp
  e2e/refactor_test/test_clone_subgraph_2/test.yml
  e2e/refactor_test/test_clone_subgraph_3/input.cyp
  e2e/refactor_test/test_clone_subgraph_3/test.yml
  e2e_correctness/refactor_test/test_clone_subgraph_path_1/input.cyp
  e2e_correctness/refactor_test/test_clone_subgraph_path_1/test.yml
  e2e_correctness/refactor_test/test_clone_subgraph_path_2/input.cyp
  e2e_correctness/refactor_test/test_clone_subgraph_path_2/test.yml
  e2e_correctness/refactor_test/test_clone_subgraph_path_3/input.cyp
  e2e_correctness/refactor_test/test_clone_subgraph_path_3/test.yml
  python/export_util.py
  python/import_util.py
Labels: type: module, status: ship it

#350 [E-refactor < E-idora] Add part of refactor procedures
  cpp/refactor_module/algorithm/refactor.cpp
  cpp/refactor_module/algorithm/refactor.hpp
  cpp/refactor_module/refactor_module.cpp
  e2e/refactor_test/test_clone_subgraph_1/input.cyp
  e2e/refactor_test/test_clone_subgraph_1/test.yml
  e2e/refactor_test/test_clone_subgraph_2/input.cyp
  e2e/refactor_test/test_clone_subgraph_2/test.yml
  e2e/refactor_test/test_clone_subgraph_3/input.cyp
  e2e/refactor_test/test_clone_subgraph_3/test.yml
  e2e/refactor_test/test_online_categorize_1/input.cyp
  e2e/refactor_test/test_online_categorize_1/test.yml
  e2e/refactor_test/test_online_categorize_2/input.cyp
  e2e/refactor_test/test_online_categorize_2/test.yml
  e2e/refactor_test/test_online_categorize_3/input.cyp
  e2e/refactor_test/test_online_categorize_3/test.yml
  e2e_correctness/refactor_test/test_clone_nodes1/input.cyp
  e2e_correctness/refactor_test/test_clone_nodes1/test.yml
  e2e_correctness/refactor_test/test_clone_nodes2/input.cyp
  e2e_correctness/refactor_test/test_clone_nodes2/test.yml
  e2e_correctness/refactor_test/test_clone_nodes3/input.cyp
  e2e_correctness/refactor_test/test_clone_nodes3/test.yml
  e2e_correctness/refactor_test/test_clone_subgraph_path_1/input.cyp
  e2e_correctness/refactor_test/test_clone_subgraph_path_1/test.yml
  e2e_correctness/refactor_test/test_clone_subgraph_path_2/input.cyp
  e2e_correctness/refactor_test/test_clone_subgraph_path_2/test.yml
  e2e_correctness/refactor_test/test_clone_subgraph_path_3/input.cyp
  e2e_correctness/refactor_test/test_clone_subgraph_path_3/test.yml
Labels: type: module, In progress

#343 [E-refactor < T376-T377] Add refactor.to and refactor.from
  cpp/refactor_module/algorithm/refactor.cpp
  cpp/refactor_module/algorithm/refactor.hpp
  cpp/refactor_module/refactor_module.cpp
  e2e_correctness/refactor_test/test_from_different/input.cyp
  e2e_correctness/refactor_test/test_from_different/test.yml
  e2e_correctness/refactor_test/test_from_same/input.cyp
  e2e_correctness/refactor_test/test_from_same/test.yml
  e2e_correctness/refactor_test/test_from_same_endpoints/input.cyp
  e2e_correctness/refactor_test/test_from_same_endpoints/test.yml
  e2e_correctness/refactor_test/test_from_to_endpoints/input.cyp
  e2e_correctness/refactor_test/test_from_to_endpoints/test.yml
  e2e_correctness/refactor_test/test_to_different/input.cyp
  e2e_correctness/refactor_test/test_to_different/test.yml
  e2e_correctness/refactor_test/test_to_same/input.cyp
  e2e_correctness/refactor_test/test_to_same/test.yml
Labels: type: module, status: ship it, Needs new memgraph

#341 [main < E-schema] Implement nodeTypeProperties and relTypeProperties
  cpp/CMakeLists.txt
  cpp/schema_module/CMakeLists.txt
  cpp/schema_module/algorithm/schema.cpp
  cpp/schema_module/algorithm/schema.hpp
  cpp/schema_module/schema_module.cpp
  e2e/schema_test/test_node_type_properties1/input.cyp
  e2e/schema_test/test_node_type_properties1/test.yml
  e2e/schema_test/test_node_type_properties2/input.cyp
  e2e/schema_test/test_node_type_properties2/test.yml
  e2e/schema_test/test_node_type_properties3/input.cyp
  e2e/schema_test/test_node_type_properties3/test.yml
  e2e/schema_test/test_rel_type_properties1/input.cyp
  e2e/schema_test/test_rel_type_properties1/test.yml
  e2e/schema_test/test_rel_type_properties2/input.cyp
  e2e/schema_test/test_rel_type_properties2/test.yml
  e2e/schema_test/test_rel_type_properties3/input.cyp
  e2e/schema_test/test_rel_type_properties3/test.yml
Labels: type: module, status: ship it

#344 [E-refactor < T372] Implement refactor.invert
  cpp/refactor_module/algorithm/refactor.cpp
  cpp/refactor_module/algorithm/refactor.hpp
  cpp/refactor_module/refactor_module.cpp
  e2e_correctness/refactor_test/test_invert1/input.cyp
  e2e_correctness/refactor_test/test_invert1/test.yml
  e2e_correctness/refactor_test/test_invert2/input.cyp
  e2e_correctness/refactor_test/test_invert2/test.yml
  e2e_correctness/refactor_test/test_invert3/input.cyp
  e2e_correctness/refactor_test/test_invert3/test.yml
Labels: type: module, status: ship it, Needs new memgraph

#347 [E-export < T345] Implement export_util.cypher.all
  e2e/export_util_test/test_export_cypher_all_1/input.cyp
  e2e/export_util_test/test_export_cypher_all_1/test.yml
  e2e/export_util_test/test_export_cypher_all_2/input.cyp
  e2e/export_util_test/test_export_cypher_all_2/test.yml
  e2e/export_util_test/test_export_cypher_all_3/input.cyp
  e2e/export_util_test/test_export_cypher_all_3/test.yml
  python/export_util.py
  python/import_util.py
Labels: status: ready, type: module

#339 [E-refactor < T370] Implement collapse node
  cpp/refactor_module/algorithm/refactor.cpp
  cpp/refactor_module/algorithm/refactor.hpp
  cpp/refactor_module/refactor_module.cpp
  e2e_correctness/refactor_test/test_collapse_node1/input.cyp
  e2e_correctness/refactor_test/test_collapse_node1/test.yml
  e2e_correctness/refactor_test/test_collapse_node2/input.cyp
  e2e_correctness/refactor_test/test_collapse_node2/test.yml
  e2e_correctness/refactor_test/test_collapse_node3/input.cyp
  e2e_correctness/refactor_test/test_collapse_node3/test.yml
Labels: type: module, status: ship it, Needs new memgraph

#359 [E-graphQL < T653] Add mgps module
  python/mgps.py
Labels: type: module, status: ship it, Docs unnecessary

#360 [E-GraphQL < T] Change procedures to fit GraphQL
  cpp/create_module/algorithm/create.hpp
  cpp/create_module/create_module.cpp
  cpp/label_module/algorithm/label.cpp
  cpp/label_module/algorithm/label.hpp
  cpp/label_module/label_module.cpp
  cpp/refactor_module/algorithm/refactor.cpp
  cpp/refactor_module/algorithm/refactor.hpp
  cpp/refactor_module/refactor_module.cpp
  e2e/label_test/test_exists_false/test.yml
  e2e/label_test/test_exists_not_node/test.yml
  e2e/label_test/test_exists_true/test.yml
  e2e/refactor_test/test_clone_subgraph_1/test.yml
  e2e/refactor_test/test_clone_subgraph_2/test.yml
  e2e/refactor_test/test_clone_subgraph_3/test.yml
  e2e_correctness/create_test/test_removeLabel_empty/test.yml
  e2e_correctness/create_test/test_removeLabel_exists/test.yml
  e2e_correctness/create_test/test_removeLabel_not_exists/test.yml
  e2e_correctness/refactor_test/test_clone_nodes1/test.yml
  e2e_correctness/refactor_test/test_clone_nodes2/test.yml
  e2e_correctness/refactor_test/test_clone_nodes3/test.yml
  e2e_correctness/refactor_test/test_clone_subgraph_path_1/test.yml
  e2e_correctness/refactor_test/test_clone_subgraph_path_2/test.yml
  e2e_correctness/refactor_test/test_clone_subgraph_path_3/test.yml
  e2e_correctness/refactor_test/test_invert1/test.yml
  e2e_correctness/refactor_test/test_invert2/test.yml
  e2e_correctness/refactor_test/test_invert3/test.yml
Labels: type: enhancement, status: ship it, status: checks failing

#361 [E-graphQL < T-collections] Change collections to abide by graphQL
  cpp/collections_module/algorithm/collections.cpp
  cpp/collections_module/algorithm/collections.hpp
  cpp/collections_module/collections_module.cpp
  e2e/collections_test/test_avg_different_types/test.yml
  e2e/collections_test/test_avg_negative/test.yml
  e2e/collections_test/test_avg_positive/test.yml
  e2e/collections_test/test_contains1/test.yml
  e2e/collections_test/test_contains2/test.yml
  e2e/collections_test/test_contains3/test.yml
  e2e/collections_test/test_contains4/test.yml
  e2e/collections_test/test_contains5/test.yml
  e2e/collections_test/test_containsS_diff_type/test.yml
  e2e/collections_test/test_containsS_sorted/test.yml
  e2e/collections_test/test_containsS_sorted_false/test.yml
  e2e/collections_test/test_containsS_unsorted/test.yml
  e2e/collections_test/test_contains_all_1/test.yml
  e2e/collections_test/test_contains_all_2/test.yml
  e2e/collections_test/test_contains_all_3/test.yml
  e2e/collections_test/test_intersection_1/test.yml
  e2e/collections_test/test_intersection_2/test.yml
  e2e/collections_test/test_intersection_3/test.yml
  e2e/collections_test/test_max_diff_types/test.yml
  e2e/collections_test/test_max_negatives/test.yml
  e2e/collections_test/test_max_positives/test.yml
  e2e/collections_test/test_min1/test.yml
  e2e/collections_test/test_min2/test.yml
  e2e/collections_test/test_min3/test.yml
  e2e/collections_test/test_min4/test.yml
  e2e/collections_test/test_pairs_allTypes/test.yml
  e2e/collections_test/test_pairs_empty/test.yml
  e2e/collections_test/test_pairs_oneType/test.yml
  e2e/collections_test/test_partition2/test.yml
  e2e/collections_test/test_partition4/test.yml
  e2e/collections_test/test_remove_all_basic/test.yml
  e2e/collections_test/test_remove_all_duplicates/test.yml
  e2e/collections_test/test_remove_all_empty/test.yml
  e2e/collections_test/test_remove_all_not_exist/test.yml
  e2e/collections_test/test_sort_diff_types/test.yml
  e2e/collections_test/test_sort_numeric/test.yml
  e2e/collections_test/test_sort_string/test.yml
  e2e/collections_test/test_sum_longs_big/test.yml
  e2e/collections_test/test_sum_longs_doubles/test.yml
  e2e/collections_test/test_sum_longs_longlong/test.yml
  e2e/collections_test/test_sum_longs_normal/test.yml
  e2e/collections_test/test_sum_notlist/test.yml
  e2e/collections_test/test_sum_numeric/test.yml
  e2e/collections_test/test_sum_string/test.yml
  e2e/collections_test/test_to_set1/test.yml
  e2e/collections_test/test_to_set2/test.yml
  e2e/collections_test/test_to_set3/test.yml
  e2e/collections_test/test_union_all1/test.yml
  e2e/collections_test/test_union_all2/test.yml
  e2e/collections_test/test_union_all3/test.yml
  e2e/collections_test/test_union_diff_types/test.yml
  e2e/collections_test/test_union_empty/test.yml
  e2e/collections_test/test_union_overlap/test.yml
Labels: status: ship it, Docs needed

#362 [E-graphQL < T- map] Add graphQL support for map
  cpp/map_module/algorithm/map.cpp
  cpp/map_module/algorithm/map.hpp
  cpp/map_module/map_module.cpp
  e2e/map_test/test_flatten1/test.yml
  e2e/map_test/test_flatten2/test.yml
  e2e/map_test/test_flatten3/test.yml
  e2e/map_test/test_fromLists1/test.yml
  e2e/map_test/test_fromLists2/test.yml
  e2e/map_test/test_fromLists3/test.yml
  e2e/map_test/test_fromPairs_diff_types/test.yml
  e2e/map_test/test_fromPairs_key_dupl/test.yml
  e2e/map_test/test_fromPairs_key_not_str/test.yml
  e2e/map_test/test_fromPairs_not_pairs/test.yml
  e2e/map_test/test_from_nodes2/input.cyp
  e2e/map_test/test_from_nodes2/test.yml
  e2e/map_test/test_from_nodes_1/input.cyp
  e2e/map_test/test_from_nodes_1/test.yml
  e2e/map_test/test_from_values_1/test.yml
  e2e/map_test/test_from_values_2/test.yml
  e2e/map_test/test_from_values_3/test.yml
  e2e/map_test/test_merge/test.yml
  e2e/map_test/test_merge_duplicate_key/test.yml
  e2e/map_test/test_merge_empty/test.yml
  e2e/map_test/test_removeKey_exists/test.yml
  e2e/map_test/test_removeKey_not_exist/test.yml
  e2e/map_test/test_removeKey_recursion/test.yml
  e2e/map_test/test_removeKey_wrong_recursion/input.cyp
  e2e/map_test/test_removeKey_wrong_recursion/test.yml
  e2e/map_test/test_removeKeys1/test.yml
  e2e/map_test/test_removeKeys2/test.yml
  e2e/map_test/test_removeKeys3/test.yml
  e2e/map_test/test_removeKeys4/test.yml
  e2e/map_test/test_removeKeys5/test.yml
  e2e/map_test/test_removeKeys6/test.yml
  e2e/map_test/test_set_key_1/test.yml
  e2e/map_test/test_set_key_2/test.yml
  e2e/map_test/test_set_key_3/test.yml
Labels: status: ship it, Docs needed

#363 [E-graphQL < T - type-props] Fix type properties for graphQL
  cpp/schema_module/algorithm/schema.cpp
  cpp/schema_module/algorithm/schema.hpp
  cpp/schema_module/schema_module.cpp
  e2e/schema_test/test_node_type_properties1/test.yml
  e2e/schema_test/test_node_type_properties2/test.yml
  e2e/schema_test/test_node_type_properties3/test.yml
  e2e/schema_test/test_rel_type_properties1/test.yml
  e2e/schema_test/test_rel_type_properties2/test.yml
  e2e/schema_test/test_rel_type_properties3/test.yml
Labels: status: ship it

#365 [main < T] Fix rust failing tests
  .github/workflows/test.yml
  rust/rsmgp-sys/src/temporal/tests.rs
Labels: status: ship it
