Repository memgraph/mage, pull requests merged in 2023-11, with the labels that each got.

#415 Modify CreateCsvFile behavior to not include newline
  cpp/csv_utils_module/algorithm/csv_utils.cpp
Labels: status: ship it, bug

#420 Regex search
  cpp/text_module/algorithm/text.cpp
  cpp/text_module/algorithm/text.hpp
  cpp/text_module/text_module.cpp
  e2e/text_test/test_regex_groups_1/input.cyp
  e2e/text_test/test_regex_groups_1/test.yml
  e2e/text_test/test_regex_groups_2/input.cyp
  e2e/text_test/test_regex_groups_2/test.yml
  e2e/text_test/test_regex_groups_3/input.cyp
  e2e/text_test/test_regex_groups_3/test.yml
Labels: feature

#423 Add impl of text.format
  cpp/text_module/CMakeLists.txt
  cpp/text_module/algorithm/text.cpp
  cpp/text_module/algorithm/text.hpp
  cpp/text_module/text_module.cpp
  e2e/text_test/test_format_1/input.cyp
  e2e/text_test/test_format_1/test.yml
  e2e/text_test/test_format_2/input.cyp
  e2e/text_test/test_format_2/test.yml
Labels: Docs needed

#366 [main < T] Update readme
  README.md
Labels: status: ready, Docs unnecessary
