Repository memgraph/mage, pull requests merged in 2023-08, with the labels that each got.

#269 [E-matija < T462] implement setProperty for create module
  cpp/create_module/algorithm/create.cpp
  cpp/create_module/algorithm/create.hpp
  cpp/create_module/create_module.cpp
  e2e_correctness/create_test/test_setProperty1/input.cyp
  e2e_correctness/create_test/test_setProperty1/test.yml
  e2e_correctness/create_test/test_setProperty2/input.cyp
  e2e_correctness/create_test/test_setProperty2/test.yml
  e2e_correctness/create_test/test_setProperty3/input.cyp
  e2e_correctness/create_test/test_setProperty3/test.yml
Labels: status: ship it

#267 [E-Ivan < T393] Implement from_values on map
  cpp/map_module/algorithm/map.cpp
  cpp/map_module/algorithm/map.hpp
  cpp/map_module/map_module.cpp
  e2e/map_test/test_from_values_1/input.cyp
  e2e/map_test/test_from_values_1/test.yml
  e2e/map_test/test_from_values_2/input.cyp
  e2e/map_test/test_from_values_2/test.yml
  e2e/map_test/test_from_values_3/input.cyp
  e2e/map_test/test_from_values_3/test.yml
Labels: status: ship it

#270 [E-ivan < T390] Implement from_nodes on map
  cpp/map_module/algorithm/map.cpp
  cpp/map_module/algorithm/map.hpp
  cpp/map_module/map_module.cpp
Labels: status: ship it

#234 [E-collections < E-ivan-collections] Add part of collections functions
  cpp/collections_module/algorithm/collections.cpp
  cpp/collections_module/algorithm/collections.hpp
  cpp/collections_module/collections_module.cpp
  e2e/collections_test/test_avg_different_types/input.cyp
  e2e/collections_test/test_avg_different_types/test.yml
  e2e/collections_test/test_avg_negative/input.cyp
  e2e/collections_test/test_avg_negative/test.yml
  e2e/collections_test/test_avg_positive/input.cyp
  e2e/collections_test/test_avg_positive/test.yml
  e2e/collections_test/test_contains_all_1/input.cyp
  e2e/collections_test/test_contains_all_1/test.yml
  e2e/collections_test/test_contains_all_2/input.cyp
  e2e/collections_test/test_contains_all_2/test.yml
  e2e/collections_test/test_contains_all_3/input.cyp
  e2e/collections_test/test_contains_all_3/test.yml
  e2e/collections_test/test_intersection_1/input.cyp
  e2e/collections_test/test_intersection_1/test.yml
  e2e/collections_test/test_intersection_2/input.cyp
  e2e/collections_test/test_intersection_2/test.yml
  e2e/collections_test/test_intersection_3/input.cyp
  e2e/collections_test/test_intersection_3/test.yml
  e2e/collections_test/test_sum_longs_big/input.cyp
  e2e/collections_test/test_sum_longs_big/test.yml
  e2e/collections_test/test_sum_longs_doubles/input.cyp
  e2e/collections_test/test_sum_longs_doubles/test.yml
  e2e/collections_test/test_sum_longs_longlong/input.cyp
  e2e/collections_test/test_sum_longs_longlong/test.yml
  e2e/collections_test/test_sum_longs_normal/input.cyp
  e2e/collections_test/test_sum_longs_normal/test.yml
  e2e/collections_test/test_unionAll1/test.yml
  e2e/collections_test/test_unionAll2/test.yml
  e2e/collections_test/test_union_all1/input.cyp
  e2e/collections_test/test_union_all1/test.yml
  e2e/collections_test/test_union_all2/input.cyp
  e2e/collections_test/test_union_all2/test.yml
  e2e/collections_test/test_union_all3/input.cyp
  e2e/collections_test/test_union_all3/test.yml
Labels: status: ship it

#272 [E-map < E-ivan] Implement map procedures
  cpp/map_module/algorithm/map.cpp
  cpp/map_module/algorithm/map.hpp
  cpp/map_module/map_module.cpp
  e2e/map_test/test_from_values_1/input.cyp
  e2e/map_test/test_from_values_1/test.yml
  e2e/map_test/test_from_values_2/input.cyp
  e2e/map_test/test_from_values_2/test.yml
  e2e/map_test/test_from_values_3/input.cyp
  e2e/map_test/test_from_values_3/test.yml
  e2e/map_test/test_set_key_1/input.cyp
  e2e/map_test/test_set_key_1/test.yml
  e2e/map_test/test_set_key_2/input.cyp
  e2e/map_test/test_set_key_2/test.yml
  e2e/map_test/test_set_key_3/input.cyp
  e2e/map_test/test_set_key_3/test.yml
Labels: status: ship it

#274 [E-matija < T459] Implement remove properties function for create module
  cpp/create_module/algorithm/create.cpp
  cpp/create_module/algorithm/create.hpp
  cpp/create_module/create_module.cpp
  e2e_correctness/create_test/test_removeProperty1/input.cyp
  e2e_correctness/create_test/test_removeProperty1/test.yml
  e2e_correctness/create_test/test_removeProperty2/input.cyp
  e2e_correctness/create_test/test_removeProperty2/test.yml
  e2e_correctness/create_test/test_removeProperty3/input.cyp
  e2e_correctness/create_test/test_removeProperty3/test.yml
Labels: status: ship it

#275 [E-matija < T456] Implement nodes function for create module
  cpp/create_module/algorithm/create.cpp
  cpp/create_module/algorithm/create.hpp
  cpp/create_module/create_module.cpp
  e2e_correctness/create_test/test_nodes1/input.cyp
  e2e_correctness/create_test/test_nodes1/test.yml
  e2e_correctness/create_test/test_nodes2/input.cyp
  e2e_correctness/create_test/test_nodes2/test.yml
  e2e_correctness/create_test/test_nodes3/input.cyp
  e2e_correctness/create_test/test_nodes3/test.yml
Labels: status: ship it

#286 [E-create < E-matija-create] Merge E-matija-create into E-create
  cpp/create_module/algorithm/create.cpp
  cpp/create_module/algorithm/create.hpp
  cpp/create_module/create_module.cpp
  e2e_correctness/create_test/test_nodes1/input.cyp
  e2e_correctness/create_test/test_nodes1/test.yml
  e2e_correctness/create_test/test_nodes2/input.cyp
  e2e_correctness/create_test/test_nodes2/test.yml
  e2e_correctness/create_test/test_nodes3/input.cyp
  e2e_correctness/create_test/test_nodes3/test.yml
  e2e_correctness/create_test/test_removeProperty1/input.cyp
  e2e_correctness/create_test/test_removeProperty1/test.yml
  e2e_correctness/create_test/test_removeProperty2/input.cyp
  e2e_correctness/create_test/test_removeProperty2/test.yml
  e2e_correctness/create_test/test_removeProperty3/input.cyp
  e2e_correctness/create_test/test_removeProperty3/test.yml
  e2e_correctness/create_test/test_setProperty1/input.cyp
  e2e_correctness/create_test/test_setProperty1/test.yml
  e2e_correctness/create_test/test_setProperty2/input.cyp
  e2e_correctness/create_test/test_setProperty2/test.yml
  e2e_correctness/create_test/test_setProperty3/input.cyp
  e2e_correctness/create_test/test_setProperty3/test.yml
Labels: status: ship it

#276 [main < fix property comparison bug] Fix property comparison bug
  e2e_correctness/query_neo_mem.py
Labels: status: ship it

#280 [E-ivan < T457] Implement create.relationship
  cpp/create_module/algorithm/create.cpp
  cpp/create_module/algorithm/create.hpp
  cpp/create_module/create_module.cpp
  e2e_correctness/create_test/test_relationship_1/input.cyp
  e2e_correctness/create_test/test_relationship_1/test.yml
  e2e_correctness/create_test/test_relationship_2/input.cyp
  e2e_correctness/create_test/test_relationship_2/test.yml
  e2e_correctness/create_test/test_relationship_3/input.cyp
  e2e_correctness/create_test/test_relationship_3/test.yml
Labels: status: ship it

#273 [E-idora-create < T461-MAGE] Implement set properties for create functions
  cpp/create_module/algorithm/create.cpp
  cpp/create_module/algorithm/create.hpp
  cpp/create_module/create_module.cpp
  e2e_correctness/create_test/test_setProperties/input.cyp
  e2e_correctness/create_test/test_setProperties/test.yml
  e2e_correctness/create_test/test_setProperties_empty/input.cyp
  e2e_correctness/create_test/test_setProperties_empty/test.yml
  e2e_correctness/create_test/test_setProperties_list/input.cyp
  e2e_correctness/create_test/test_setProperties_list/test.yml
Labels: status: ship it

#305 [main < T611] Add testing paths and relationships in e2e
  e2e/test_module.py
Labels: status: ship it

#302 [E-nodes < T478] Implement nodes.delete
  cpp/nodes_module/algorithm/nodes.cpp
  cpp/nodes_module/algorithm/nodes.hpp
  cpp/nodes_module/nodes_module.cpp
  e2e_correctness/nodes_test/test_delete_id/input.cyp
  e2e_correctness/nodes_test/test_delete_id/test.yml
  e2e_correctness/nodes_test/test_delete_ids/input.cyp
  e2e_correctness/nodes_test/test_delete_ids/test.yml
  e2e_correctness/nodes_test/test_delete_node/input.cyp
  e2e_correctness/nodes_test/test_delete_node/test.yml
  e2e_correctness/nodes_test/test_delete_nodes/input.cyp
  e2e_correctness/nodes_test/test_delete_nodes/test.yml
Labels: status: ready

#300 [E-node < T501] Implement node.relationship_types
  cpp/node_module/algorithm/node.cpp
  cpp/node_module/algorithm/node.hpp
  cpp/node_module/node_module.cpp
  e2e/node_test/test_relationship_types_1/input.cyp
  e2e/node_test/test_relationship_types_1/test.yml
  e2e/node_test/test_relationship_types_2/input.cyp
  e2e/node_test/test_relationship_types_2/test.yml
  e2e/node_test/test_relationship_types_3/input.cyp
  e2e/node_test/test_relationship_types_3/test.yml
Labels: status: draft

#301 [E-nodes < T502] Implement nodes.relationship_types
  cpp/nodes_module/algorithm/nodes.cpp
  cpp/nodes_module/algorithm/nodes.hpp
  cpp/nodes_module/nodes_module.cpp
  e2e/nodes_test/test_relationship_types_id/input.cyp
  e2e/nodes_test/test_relationship_types_id/test.yml
  e2e/nodes_test/test_relationship_types_ids/input.cyp
  e2e/nodes_test/test_relationship_types_ids/test.yml
  e2e/nodes_test/test_relationship_types_node/input.cyp
  e2e/nodes_test/test_relationship_types_node/test.yml
  e2e/nodes_test/test_relationship_types_nodes/input.cyp
  e2e/nodes_test/test_relationship_types_nodes/test.yml
Labels: status: draft

#287 [main < T583] Implement text.join
  cpp/CMakeLists.txt
  cpp/text_module/CMakeLists.txt
  cpp/text_module/algorithm/text.cpp
  cpp/text_module/algorithm/text.hpp
  cpp/text_module/text_module.cpp
  e2e/text_test/test_join_1/input.cyp
  e2e/text_test/test_join_1/test.yml
  e2e/text_test/test_join_2/input.cyp
  e2e/text_test/test_join_2/test.yml
  e2e/text_test/test_join_3/input.cyp
  e2e/text_test/test_join_3/test.yml
Labels: status: ship it

#295 [main < fix property bug] Fix empty properties bug
  e2e_correctness/query_neo_mem.py
Labels: status: ship it

#278 [E-idora-create < T458-MAGE] Implement remove labels for create functions
  cpp/create_module/algorithm/create.cpp
  cpp/create_module/algorithm/create.hpp
  cpp/create_module/create_module.cpp
  e2e_correctness/create_test/test_removeLabel_empty/input.cyp
  e2e_correctness/create_test/test_removeLabel_empty/test.yml
  e2e_correctness/create_test/test_removeLabel_exists/input.cyp
  e2e_correctness/create_test/test_removeLabel_exists/test.yml
  e2e_correctness/create_test/test_removeLabel_not_exists/input.cyp
  e2e_correctness/create_test/test_removeLabel_not_exists/test.yml
Labels: status: ship it, status: checks failing

#279 [E-idora-create < T464-MAGE] Implement set rel property for create functions
  cpp/CMakeLists.txt
  cpp/create_module/algorithm/create.cpp
  cpp/create_module/algorithm/create.hpp
  cpp/create_module/create_module.cpp
  e2e_correctness/create_test/test_setRelProperty_change/input.cyp
  e2e_correctness/create_test/test_setRelProperty_change/test.yml
  e2e_correctness/create_test/test_setRelProperty_new/input.cyp
  e2e_correctness/create_test/test_setRelProperty_new/test.yml
Labels: status: ship it

#293 [E-nodes < T465] Implement nodes.link
  cpp/nodes_module/algorithm/nodes.cpp
  cpp/nodes_module/algorithm/nodes.hpp
  cpp/nodes_module/nodes_module.cpp
  e2e_correctness/nodes_test/test_link1/input.cyp
  e2e_correctness/nodes_test/test_link1/test.yml
  e2e_correctness/nodes_test/test_link2/input.cyp
  e2e_correctness/nodes_test/test_link2/test.yml
  e2e_correctness/nodes_test/test_link3/input.cyp
  e2e_correctness/nodes_test/test_link3/test.yml
Labels: status: ship it

#303 [E-node < T498] Implement relationship_exists
  cpp/node_module/algorithm/node.cpp
  cpp/node_module/algorithm/node.hpp
  cpp/node_module/node_module.cpp
  e2e/node_test/test_rel-exists_in/input.cyp
  e2e/node_test/test_rel-exists_in/test.yml
  e2e/node_test/test_rel-exists_in_false/input.cyp
  e2e/node_test/test_rel-exists_in_false/test.yml
  e2e/node_test/test_rel-exists_in_or_out/input.cyp
  e2e/node_test/test_rel-exists_in_or_out/test.yml
  e2e/node_test/test_rel-exists_in_or_out_false/input.cyp
  e2e/node_test/test_rel-exists_in_or_out_false/test.yml
  e2e/node_test/test_rel-exists_multiple/input.cyp
  e2e/node_test/test_rel-exists_multiple/test.yml
  e2e/node_test/test_rel-exists_no_pattern/input.cyp
  e2e/node_test/test_rel-exists_no_pattern/test.yml
  e2e/node_test/test_rel-exists_no_pattern_false/input.cyp
  e2e/node_test/test_rel-exists_no_pattern_false/test.yml
  e2e/node_test/test_rel-exists_out/input.cyp
  e2e/node_test/test_rel-exists_out/test.yml
  e2e/node_test/test_rel-exists_out_false/input.cyp
  e2e/node_test/test_rel-exists_out_false/test.yml
Labels: status: ready, status: resolve conflicts

#316 [E-neighbors < T485] Implement byhop procedure
  cpp/neighbors_module/algorithm/neighbors.cpp
  cpp/neighbors_module/algorithm/neighbors.hpp
  cpp/neighbors_module/neighbors_module.cpp
  e2e/neighbors_test/test_byhop/input.cyp
  e2e/neighbors_test/test_byhop/test.yml
  e2e/neighbors_test/test_byhop_direction/input.cyp
  e2e/neighbors_test/test_byhop_direction/test.yml
  e2e/neighbors_test/test_byhop_multiple/input.cyp
  e2e/neighbors_test/test_byhop_multiple/test.yml
Labels: status: ready

#309 [E-ivan < T460] Implement create.remove_rel_properties
  cpp/create_module/algorithm/create.cpp
  cpp/create_module/algorithm/create.hpp
  cpp/create_module/create_module.cpp
  e2e_correctness/create_test/test_remove_rel_properties_id/input.cyp
  e2e_correctness/create_test/test_remove_rel_properties_id/test.yml
  e2e_correctness/create_test/test_remove_rel_properties_ids/input.cyp
  e2e_correctness/create_test/test_remove_rel_properties_ids/test.yml
  e2e_correctness/create_test/test_remove_rel_properties_relationship/input.cyp
  e2e_correctness/create_test/test_remove_rel_properties_relationship/test.yml
  e2e_correctness/create_test/test_remove_rel_properties_relationships/input.cyp
  e2e_correctness/create_test/test_remove_rel_properties_relationships/test.yml
Labels: status: ready

#304 [main < T510] Implement label
  cpp/CMakeLists.txt
  cpp/label_module/CMakeLists.txt
  cpp/label_module/algorithm/label.cpp
  cpp/label_module/algorithm/label.hpp
  cpp/label_module/label_module.cpp
  e2e/label_test/test_exists_false/input.cyp
  e2e/label_test/test_exists_false/test.yml
  e2e/label_test/test_exists_not_node/input.cyp
  e2e/label_test/test_exists_not_node/test.yml
  e2e/label_test/test_exists_true/input.cyp
  e2e/label_test/test_exists_true/test.yml
Labels: status: ship it

#298 [E-node < T499] Implement node.relationshipsExist
  cpp/node_module/algorithm/node.cpp
  cpp/node_module/algorithm/node.hpp
  cpp/node_module/node_module.cpp
  e2e/node_test/test_relationshipsExist1/input.cyp
  e2e/node_test/test_relationshipsExist1/test.yml
  e2e/node_test/test_relationshipsExist2/input.cyp
  e2e/node_test/test_relationshipsExist2/test.yml
  e2e/node_test/test_relationshipsExist3/input.cyp
  e2e/node_test/test_relationshipsExist3/test.yml
Labels: status: ship it, status: resolve conflicts

#318 [E-add-create-functions < E-idora] Add part of create functions
  cpp/create_module/algorithm/create.cpp
  cpp/create_module/algorithm/create.hpp
  cpp/create_module/create_module.cpp
  e2e_correctness/create_test/test_node/input.cyp
  e2e_correctness/create_test/test_node/test.yml
  e2e_correctness/create_test/test_node_double_label/input.cyp
  e2e_correctness/create_test/test_node_double_label/test.yml
  e2e_correctness/create_test/test_node_null_prop/input.cyp
  e2e_correctness/create_test/test_node_null_prop/test.yml
  e2e_correctness/create_test/test_removeLabel_empty/input.cyp
  e2e_correctness/create_test/test_removeLabel_empty/test.yml
  e2e_correctness/create_test/test_removeLabel_exists/input.cyp
  e2e_correctness/create_test/test_removeLabel_exists/test.yml
  e2e_correctness/create_test/test_removeLabel_not_exists/input.cyp
  e2e_correctness/create_test/test_removeLabel_not_exists/test.yml
  e2e_correctness/create_test/test_setProperties/input.cyp
  e2e_correctness/create_test/test_setProperties/test.yml
  e2e_correctness/create_test/test_setProperties_empty/input.cyp
  e2e_correctness/create_test/test_setProperties_empty/test.yml
  e2e_correctness/create_test/test_setProperties_list/input.cyp
  e2e_correctness/create_test/test_setProperties_list/test.yml
  e2e_correctness/create_test/test_setRelProperty_change/input.cyp
  e2e_correctness/create_test/test_setRelProperty_change/test.yml
  e2e_correctness/create_test/test_setRelProperty_new/input.cyp
  e2e_correctness/create_test/test_setRelProperty_new/test.yml
Labels: status: ready

#324 [main < T324] Reliable llm_util output
  e2e/llm_util_test/test_schema_default_with_relationship_props/test.yml
  e2e/llm_util_test/test_schema_default_without_relationship_props/test.yml
  e2e/llm_util_test/test_schema_prompt_ready_ignore_case/test.yml
  e2e/llm_util_test/test_schema_prompt_ready_with_relationship_props/test.yml
  e2e/llm_util_test/test_schema_prompt_ready_without_relationship_props/test.yml
  python/llm_util.py
Labels: type: bug, lang: python, status: ready

#297 [E-nodes < T500] Implement nodes.relationships.exist
  cpp/nodes_module/algorithm/nodes.cpp
  cpp/nodes_module/algorithm/nodes.hpp
  cpp/nodes_module/nodes_module.cpp
  e2e/nodes_test/test_relationships_exist1/input.cyp
  e2e/nodes_test/test_relationships_exist1/test.yml
  e2e/nodes_test/test_relationships_exist2/input.cyp
  e2e/nodes_test/test_relationships_exist2/test.yml
  e2e/nodes_test/test_relationships_exist3/input.cyp
  e2e/nodes_test/test_relationships_exist3/test.yml
Labels: status: ship it

#310 [E-path < T480] Implement path expand function
  cpp/CMakeLists.txt
  cpp/path_module/algorithm/path.cpp
  cpp/path_module/algorithm/path.hpp
  cpp/path_module/path_module.cpp
  e2e/path_test/test_expand1/input.cyp
  e2e/path_test/test_expand1/test.yml
  e2e/path_test/test_expand2/input.cyp
  e2e/path_test/test_expand2/test.yml
  e2e/path_test/test_expand3/input.cyp
  e2e/path_test/test_expand3/test.yml
  e2e/path_test/test_expand4/input.cyp
  e2e/path_test/test_expand4/test.yml
Labels: status: ship it

#315 [main < E-node] Merge node functions into main
  cpp/CMakeLists.txt
  cpp/node_module/CMakeLists.txt
  cpp/node_module/algorithm/node.cpp
  cpp/node_module/algorithm/node.hpp
  cpp/node_module/node_module.cpp
  e2e/node_test/test_rel-exists_in/input.cyp
  e2e/node_test/test_rel-exists_in/test.yml
  e2e/node_test/test_rel-exists_in_false/input.cyp
  e2e/node_test/test_rel-exists_in_false/test.yml
  e2e/node_test/test_rel-exists_in_or_out/input.cyp
  e2e/node_test/test_rel-exists_in_or_out/test.yml
  e2e/node_test/test_rel-exists_in_or_out_false/input.cyp
  e2e/node_test/test_rel-exists_in_or_out_false/test.yml
  e2e/node_test/test_rel-exists_multiple/input.cyp
  e2e/node_test/test_rel-exists_multiple/test.yml
  e2e/node_test/test_rel-exists_no_pattern/input.cyp
  e2e/node_test/test_rel-exists_no_pattern/test.yml
  e2e/node_test/test_rel-exists_no_pattern_false/input.cyp
  e2e/node_test/test_rel-exists_no_pattern_false/test.yml
  e2e/node_test/test_rel-exists_out/input.cyp
  e2e/node_test/test_rel-exists_out/test.yml
  e2e/node_test/test_rel-exists_out_false/input.cyp
  e2e/node_test/test_rel-exists_out_false/test.yml
  e2e/node_test/test_relationship_types_1/input.cyp
  e2e/node_test/test_relationship_types_1/test.yml
  e2e/node_test/test_relationship_types_2/input.cyp
  e2e/node_test/test_relationship_types_2/test.yml
  e2e/node_test/test_relationship_types_3/input.cyp
  e2e/node_test/test_relationship_types_3/test.yml
  e2e/node_test/test_relationshipsExist1/input.cyp
  e2e/node_test/test_relationshipsExist1/test.yml
  e2e/node_test/test_relationshipsExist2/input.cyp
  e2e/node_test/test_relationshipsExist2/test.yml
  e2e/node_test/test_relationshipsExist3/input.cyp
  e2e/node_test/test_relationshipsExist3/test.yml
Labels: status: ship it

#322 [main < T623] Load files in E2E tests
  e2e/test_module.py
Labels: status: ship it

#308 [main < E-add-neighbors-functions] Add neighbors procedures
  cpp/CMakeLists.txt
  cpp/neighbors_module/CMakeLists.txt
  cpp/neighbors_module/algorithm/neighbors.cpp
  cpp/neighbors_module/algorithm/neighbors.hpp
  cpp/neighbors_module/neighbors_module.cpp
  e2e/neighbors_test/test_athop/input.cyp
  e2e/neighbors_test/test_athop/test.yml
  e2e/neighbors_test/test_athop_cycle/input.cyp
  e2e/neighbors_test/test_athop_cycle/test.yml
  e2e/neighbors_test/test_athop_direction/input.cyp
  e2e/neighbors_test/test_athop_direction/test.yml
  e2e/neighbors_test/test_athop_empty_type/input.cyp
  e2e/neighbors_test/test_athop_empty_type/test.yml
  e2e/neighbors_test/test_byhop/input.cyp
  e2e/neighbors_test/test_byhop/test.yml
  e2e/neighbors_test/test_byhop_direction/input.cyp
  e2e/neighbors_test/test_byhop_direction/test.yml
  e2e/neighbors_test/test_byhop_multiple/input.cyp
  e2e/neighbors_test/test_byhop_multiple/test.yml
Labels: status: ship it
