Repository memgraph/mage, pull requests merged in 2024-11, with the labels that each got.

#527 Add missing includes due to mgp.hpp change
  cpp/graph_util_module/algorithms/ancestors.hpp
  cpp/katz_centrality_module/katz_centrality_module.cpp
  cpp/katz_centrality_module/katz_centrality_online_module.cpp
  cpp/leiden_community_detection_module/algorithm/leiden.cpp
  cpp/mg_utility/mg_utils.hpp
  cpp/node_similarity_module/algorithms/node_similarity.hpp
  cpp/pagerank_module/algorithm/pagerank.cpp
  cpp/pagerank_module/algorithm/pagerank.hpp
  cpp/path_module/algorithm/path.hpp
Labels: Docs unnecessary, bug

#528 Bring back removed modules
  .github/workflows/reusable_test.yml
  Dockerfile.release
Labels: bug

#526 Install auth modules dependencies
  Dockerfile.no_ML
  Dockerfile.release
Labels: Docs - changelog only
