Repository memgraph/mage, pull requests merged in 2024-07, with the labels that each got.

#486 Improve rc artifacts workflow
  .github/workflows/package_mage.yaml
  .github/workflows/release_artifacts.yaml
  .github/workflows/reusable_package_mage.yaml
Labels: Docs unnecessary

#483 Fix building of newly created rust modules
  setup
Labels: Docs - changelog only, bug

#487 Add workflow to promote RC to release
  .github/workflows/promote_rc_release.yaml
  .github/workflows/reusable_package_mage.yaml
Labels: Docs unnecessary

#490 Refactor testing in CI
  .github/workflows/reusable_test.yml
  .github/workflows/test.yml
  .github/workflows/test_no_ml.yml
Labels: Docs unnecessary

#491 Fix nightly build and test runs
  .github/workflows/test.yml
Labels: Docs unnecessary, bug

#492 Fix promote to release workflow
  .github/workflows/promote_rc_release.yaml
Labels: Docs unnecessary, bug

#493 Fix artifact names for release artifacts workflow
  .github/workflows/reusable_package_mage.yaml
Labels: Docs unnecessary

#495 Add support for S3 URI in test workflows
  .github/workflows/reusable_test.yml
  .github/workflows/test.yml
Labels: Docs unnecessary
