Repository memgraph/mage, pull requests merged in 2025-03, with the labels that each got.

#551 Remove mg_utils from MAGE
  cpp/CMakeLists.txt
  cpp/mg_utility/CMakeLists.txt
  cpp/mg_utility/data_structures/graph_data.hpp
  cpp/mg_utility/data_structures/graph_view.hpp
  cpp/mg_utility/mg_generate.hpp
  cpp/mg_utility/mg_graph.hpp
  cpp/mg_utility/mg_test_utils.hpp
  cpp/mg_utility/mg_utils.hpp
Labels: Docs unnecessary

#549 Improve Louvain community detection module
  cpp/community_detection_module/algorithm/louvain.cpp
  cpp/community_detection_module/algorithm/louvain.hpp
  cpp/community_detection_module/community_detection_module.cpp
Labels: Docs needed

#567 refactor release promotion to allow for missing builds
  .github/workflows/promote_rc_release.yaml
Labels: infrastructure

#566 Add malloc release
  .github/workflows/package_mage.yaml
  .github/workflows/promote_rc_release.yaml
  .github/workflows/release_artifacts.yaml
  .github/workflows/reusable_package_mage.yaml
Labels: infrastructure, Docs unnecessary

#571 Add PR test to merge_group
  .github/workflows/test.yml
Labels: infrastructure, Docs unnecessary

#554 Fix export_util.py to encode in the UTF-8
  python/export_util.py
Labels: Docs unnecessary, bug

#568 Reduce image size
  .github/workflows/package_mage.yaml
  .github/workflows/promote_rc_release.yaml
  .github/workflows/release_artifacts.yaml
  .github/workflows/reusable_package_mage.yaml
  .github/workflows/reusable_test.yml
  .github/workflows/test.yml
  Dockerfile.no_ML
  Dockerfile.release
  Dockerfile.v6mgbuild
  get_memgraph_tag.sh
  get_tag.sh
  make-dev-container.sh
  manual_test.sh
  print_image_size.sh
  python/requirements.txt
Labels: infrastructure, Docs needed

#557 Add migration from Neo4j
  python/migrate.py
Labels: Docs needed, feature, Effort - Low

#577 Set shell for memgraph user to /bin/bash
  Dockerfile.no_ML
  Dockerfile.release
Labels: Docs unnecessary

#579 Add gdb and full mage repo to relwithdebinfo image
  .github/workflows/reusable_package_mage.yaml
  Dockerfile.no_ML
  Dockerfile.release
Labels: Docs unnecessary
