Repository memgraph/mage, pull requests merged in 2025-07, with the labels that each got.

#620 Stop tagging DX in PR template
  .github/pull_request_template.md
Labels: infrastructure, Docs unnecessary

#629 Fix CVE scan false positive
  scripts/scan_languages.py
  scripts/triage.json
Labels: infrastructure, Docs unnecessary

#623 Add `refactor.mergeNodes` procedure
  cpp/refactor_module/algorithm/refactor.cpp
  cpp/refactor_module/algorithm/refactor.hpp
  cpp/refactor_module/refactor_module.cpp
  e2e/refactor_test/test_merge_nodes_asterisk/input.cyp
  e2e/refactor_test/test_merge_nodes_asterisk/test.yml
  e2e/refactor_test/test_merge_nodes_case_insensitive/input.cyp
  e2e/refactor_test/test_merge_nodes_case_insensitive/test.yml
  e2e/refactor_test/test_merge_nodes_combine_basic/input.cyp
  e2e/refactor_test/test_merge_nodes_combine_basic/test.yml
  e2e/refactor_test/test_merge_nodes_combine_basic_2/input.cyp
  e2e/refactor_test/test_merge_nodes_combine_basic_2/test.yml
  e2e/refactor_test/test_merge_nodes_combine_merge/input.cyp
  e2e/refactor_test/test_merge_nodes_combine_merge/test.yml
  e2e/refactor_test/test_merge_nodes_discard_basic/input.cyp
  e2e/refactor_test/test_merge_nodes_discard_basic/test.yml
  e2e/refactor_test/test_merge_nodes_invalid_empty_nodes/input.cyp
  e2e/refactor_test/test_merge_nodes_invalid_empty_nodes/test.yml
  e2e/refactor_test/test_merge_nodes_invalid_merge_rels_value/input.cyp
  e2e/refactor_test/test_merge_nodes_invalid_merge_rels_value/test.yml
  e2e/refactor_test/test_merge_nodes_merge_false/input.cyp
  e2e/refactor_test/test_merge_nodes_merge_false/test.yml
  e2e/refactor_test/test_merge_nodes_merge_rels/input.cyp
  e2e/refactor_test/test_merge_nodes_merge_rels/test.yml
  e2e/refactor_test/test_merge_nodes_override_basic/input.cyp
  e2e/refactor_test/test_merge_nodes_override_basic/test.yml
  e2e/refactor_test/test_merge_nodes_overwrite_basic/input.cyp
  e2e/refactor_test/test_merge_nodes_overwrite_basic/test.yml
Labels: Docs needed, apoc, feature, customer

#630 Fix artifact upload for CVE scan
  scripts/cve_message.py
  scripts/scan_languages.py
Labels: infrastructure, Docs unnecessary, bug

#632 Increase RC build automation
  .github/workflows/build_rc.yml
  .github/workflows/release_artifacts.yaml
  .github/workflows/reusable_package_mage.yaml
  .github/workflows/reusable_test.yml
  .github/workflows/test.yml
Labels: infrastructure, Docs unnecessary

#634 Clone latest version of `date.py` for MAGE's implementation
  e2e/date_test/test_convert_format/input.cyp
  e2e/date_test/test_convert_format/test.yml
  e2e/date_test/test_online_convert_format/input.cyp
  e2e/date_test/test_online_convert_format/test.yml
  python/date.py
Labels: Docs unnecessary, bug

#640 Add normalization of text characters in `text.distance`
  cpp/text_module/CMakeLists.txt
  cpp/text_module/algorithm/text.cpp
  cpp/text_module/utf8.h
  cpp/text_module/utf8/checked.h
  cpp/text_module/utf8/core.h
  cpp/text_module/utf8/cpp11.h
  cpp/text_module/utf8/cpp17.h
  cpp/text_module/utf8/cpp20.h
  cpp/text_module/utf8/unchecked.h
  e2e/text_test/test_distance_unicode/input.cyp
  e2e/text_test/test_distance_unicode/test.yml
Labels: Docs - changelog only, apoc, bug, community

#641 Add optimization for `text.regreplace` by caching regex pattern
  cpp/text_module/algorithm/text.cpp
  cpp/text_module/algorithm/text.hpp
Labels: Docs - changelog only, apoc, bug, community, customer

#646 fix: cve-bin-tool OSV update
  .github/workflows/update_cve_database.yml
Labels: infrastructure, Docs unnecessary

#649 Disable cve-bin-tool on weekly CVE scan
  .github/workflows/cve_scan.yml
  .github/workflows/update_cve_database.yml
Labels: infrastructure, Docs unnecessary
