Repository memgraph/mage, pull requests merged in 2025-01, with the labels that each got.

#538 Rewrite UUID module to be same as on Memgraph main repo
  .github/workflows/reusable_test.yml
  Dockerfile
  Dockerfile.cugraph
  Dockerfile.no_ML
  Dockerfile.release
  cpp/CMakeLists.txt
  cpp/uuid_module/CMakeLists.txt
  cpp/uuid_module/uuid_module.cpp
  e2e/test_module.py
  e2e_correctness/test_modules.py
Labels: Docs - changelog only, feature, breaking

#536 Rewrite refactor modules to not use deleted API
  README.md
  cpp/CMakeLists.txt
  cpp/refactor_module/algorithm/refactor.cpp
  cpp/refactor_module/algorithm/refactor.hpp
  e2e/test_module.py
  e2e_correctness/test_modules.py
Labels: Docs - changelog only, apoc, breaking

#542 Fix e2e_correctness tests
  .github/workflows/reusable_test.yml
  cpp/refactor_module/algorithm/refactor.cpp
  run_e2e_correctness_tests.sh
  test_e2e_correctness.py
Labels: infrastructure, Docs - changelog only, bug

#535 Upgrade Mage to Ubuntu 24.04
  .github/workflows/docker_publish.yml
  .github/workflows/release_artifacts.yaml
  .github/workflows/reusable_package_mage.yaml
  .github/workflows/reusable_test.yml
  .github/workflows/test.yml
  Dockerfile.no_ML
  Dockerfile.release
  README.md
  e2e/kmeans_test/test_kmeans_small/test.yml
  python/kmeans.py
  python/requirements.txt
  python/requirements_no_ml.txt
  python/tests/requirements.txt
Labels: infrastructure, Docs needed, breaking
