Repository memgraph/mage, pull requests merged in 2025-04, with the labels that each got.

#588 Betweenness centrality improvements
  cpp/betweenness_centrality_module/algorithm/betweenness_centrality.cpp
  cpp/betweenness_centrality_module/algorithm/betweenness_centrality.hpp
  cpp/betweenness_centrality_module/betweenness_centrality_module.cpp
  cpp/betweenness_centrality_module/betweenness_centrality_online_test.cpp
  cpp/betweenness_centrality_module/betweenness_centrality_test.cpp
Labels: Docs needed, enhancement

#586 Remove QEMU step from packaging workflow
  .github/workflows/reusable_package_mage.yaml
Labels: infrastructure, Docs unnecessary

#584 Use self hosted runners for building MAGE
  .github/workflows/docker_publish.yml
  .github/workflows/promote_rc_release.yaml
  .github/workflows/release_artifacts.yaml
Labels: infrastructure, Docs unnecessary

#587 Speed up ARM build
  .github/workflows/reusable_package_mage.yaml
  .github/workflows/reusable_test.yml
  Dockerfile.no_ML
  Dockerfile.release
  make-dev-container.sh
  python/requirements.txt
Labels: infrastructure, Docs - changelog only

#558 Migrate via Apache Arrow Flight
  python/migrate.py
  python/requirements.txt
  python/requirements_no_ml.txt
Labels: Docs needed, feature

#560 Migrate via DuckDB
  python/migrate.py
  python/requirements.txt
  python/requirements_no_ml.txt
Labels: Docs needed, feature

#561 Migrate from another Memgraph instance
  python/migrate.py
Labels: Docs needed, feature

#590 Remove MAGE Build Without ML
  .github/workflows/package_mage.yaml
  .github/workflows/promote_rc_release.yaml
  .github/workflows/release_artifacts.yaml
  .github/workflows/reusable_package_mage.yaml
  .github/workflows/reusable_test.yml
  .github/workflows/test.yml
  Dockerfile.no_ML
  python/requirements_no_ml.txt
Labels: infrastructure, Docs needed

#594 Move memgraph user's home directory
  Dockerfile.release
Labels: infrastructure, Docs - changelog only, bug

#572 Migrate from servicenow
  python/migrate.py
Labels: Docs unnecessary, feature

#597 Add Smoke Testing
  smoke-release-testing/.gitignore
  smoke-release-testing/README.md
  smoke-release-testing/config/k8s-ha-values.yaml
  smoke-release-testing/experiment.bash
  smoke-release-testing/flags.py
  smoke-release-testing/init.bash
  smoke-release-testing/init_mac.bash
  smoke-release-testing/inspect_files.bash
  smoke-release-testing/mgconsole/README.md
  smoke-release-testing/mgconsole/auth_roles.bash
  smoke-release-testing/mgconsole/backwards.bash
  smoke-release-testing/mgconsole/basic_auth.bash
  smoke-release-testing/mgconsole/dynamic_algos.bash
  smoke-release-testing/mgconsole/edge_type_operations.bash
  smoke-release-testing/mgconsole/functions.bash
  smoke-release-testing/mgconsole/ha.bash
  smoke-release-testing/mgconsole/impersonate.bash
  smoke-release-testing/mgconsole/indices.bash
  smoke-release-testing/mgconsole/k8s.bash
  smoke-release-testing/mgconsole/label_operations.bash
  smoke-release-testing/mgconsole/monitoring.bash
  smoke-release-testing/mgconsole/multi_tenancy.bash
  smoke-release-testing/mgconsole/query.bash
  smoke-release-testing/mgconsole/query_modules.bash
  smoke-release-testing/mgconsole/session_trace.bash
  smoke-release-testing/mgconsole/show_schema.bash
  smoke-release-testing/mgconsole/spatial.bash
  smoke-release-testing/mgconsole/storage.bash
  smoke-release-testing/mgconsole/streams.bash
  smoke-release-testing/mgconsole/template.bash
  smoke-release-testing/mgconsole/ttl.bash
  smoke-release-testing/mgconsole/type_constraints.bash
  smoke-release-testing/mgconsole/vector_search.bash
  smoke-release-testing/python/gqla.py
  smoke-release-testing/python/neo.py
  smoke-release-testing/query_modules/basic.cpp
  smoke-release-testing/requirements.txt
  smoke-release-testing/test.bash
  smoke-release-testing/utils.bash
  smoke-release-testing/validator.py
Labels: infrastructure

#601 Added missing ODBC driver for SQL
  Dockerfile.release
Labels: infrastructure, Docs unnecessary, bug

#602 Fix event_name check
  .github/workflows/daily_build.yml
Labels: infrastructure, Docs unnecessary, bug

#606 Fix MAGE packaging workflow so it uses package cache
  .github/workflows/reusable_package_mage.yaml
Labels: infrastructure, Docs unnecessary
