Repository memgraph/mage, pull requests merged in 2025-08, with the labels that each got.

#652 Implement math.round
  cpp/CMakeLists.txt
  cpp/math_module/CMakeLists.txt
  cpp/math_module/algorithm/math.cpp
  cpp/math_module/algorithm/math.hpp
  cpp/math_module/math_module.cpp
  e2e/math_test/test_ceiling_mode/input.cyp
  e2e/math_test/test_ceiling_mode/test.yml
  e2e/math_test/test_default_args/input.cyp
  e2e/math_test/test_default_args/test.yml
  e2e/math_test/test_down_mode/input.cyp
  e2e/math_test/test_down_mode/test.yml
  e2e/math_test/test_down_mode_negative/input.cyp
  e2e/math_test/test_down_mode_negative/test.yml
  e2e/math_test/test_floor_mode/input.cyp
  e2e/math_test/test_floor_mode/test.yml
  e2e/math_test/test_half_down_mode/input.cyp
  e2e/math_test/test_half_down_mode/test.yml
  e2e/math_test/test_half_even_mode/input.cyp
  e2e/math_test/test_half_even_mode/test.yml
  e2e/math_test/test_half_even_mode_odd/input.cyp
  e2e/math_test/test_half_even_mode_odd/test.yml
  e2e/math_test/test_half_up_mode/input.cyp
  e2e/math_test/test_half_up_mode/test.yml
  e2e/math_test/test_unnecessary_mode/input.cyp
  e2e/math_test/test_unnecessary_mode/test.yml
  e2e/math_test/test_up_mode/input.cyp
  e2e/math_test/test_up_mode/test.yml
  e2e/math_test/test_up_mode_negative/input.cyp
  e2e/math_test/test_up_mode_negative/test.yml
Labels: Docs needed, apoc

#653 Fix json_util.to_json and json_util.from_json_list
  e2e/json_util_test/test_from_json_list/input.cyp
  e2e/json_util_test/test_from_json_list/test.yml
  e2e/json_util_test/test_to_json/input.cyp
  e2e/json_util_test/test_to_json/test.yml
  python/mage/json_util/core.py
  python/tests/json_util/test_json_util.py
Labels: apoc, bug

#607 Add v3.4 smoke tests and basic HA cluster upgrade test
  .github/workflows/reusable_smoke_tests.yml
  smoke-release-testing/experiment.bash
  smoke-release-testing/k8s/run.bash
  smoke-release-testing/k8s/values-ha.yaml
  smoke-release-testing/k8s/values-single.yaml
  smoke-release-testing/mgconsole/indices.bash
  smoke-release-testing/mgconsole/vector_search.bash
  smoke-release-testing/test_ha_memgraph.bash
  smoke-release-testing/test_single_mage.bash
  smoke-release-testing/utils.bash
  smoke-release-testing/validator.py
Labels: type: test, infrastructure, Docs unnecessary

#651 Add workflow to be triggered when PR gets merged in Memgraph
  .github/workflows/pr_build.yml
  .github/workflows/reusable_package_mage.yaml
  scripts/pr_build_vars.py
Labels: infrastructure, Docs unnecessary
